[2025-04-24T23:09:29.750+0000] {processor.py:186} INFO - Started process (PID=75) to work on /opt/airflow/dags/user_processing.py
[2025-04-24T23:09:29.753+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2025-04-24T23:09:29.762+0000] {logging_mixin.py:190} INFO - [2025-04-24T23:09:29.761+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2025-04-24T23:09:30.070+0000] {logging_mixin.py:190} INFO - [2025-04-24T23:09:29.962+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 4, in <module>
    from airflow.providers.http.operators.http import SimpleHttpOperator
ImportError: cannot import name 'SimpleHttpOperator' from 'airflow.providers.http.operators.http' (/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/http/operators/http.py)
[2025-04-24T23:09:30.090+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2025-04-24T23:09:30.158+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/user_processing.py took 0.424 seconds
[2025-04-24T23:10:00.351+0000] {processor.py:186} INFO - Started process (PID=84) to work on /opt/airflow/dags/user_processing.py
[2025-04-24T23:10:00.352+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2025-04-24T23:10:00.356+0000] {logging_mixin.py:190} INFO - [2025-04-24T23:10:00.355+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2025-04-24T23:10:00.418+0000] {logging_mixin.py:190} INFO - [2025-04-24T23:10:00.403+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 4, in <module>
    from airflow.providers.http.operators.http import SimpleHttpOperator
ImportError: cannot import name 'SimpleHttpOperator' from 'airflow.providers.http.operators.http' (/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/http/operators/http.py)
[2025-04-24T23:10:00.434+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2025-04-24T23:10:00.498+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/user_processing.py took 0.157 seconds
[2025-04-24T23:10:31.266+0000] {processor.py:186} INFO - Started process (PID=92) to work on /opt/airflow/dags/user_processing.py
[2025-04-24T23:10:31.279+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2025-04-24T23:10:31.289+0000] {logging_mixin.py:190} INFO - [2025-04-24T23:10:31.288+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2025-04-24T23:10:31.341+0000] {logging_mixin.py:190} INFO - [2025-04-24T23:10:31.327+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 4, in <module>
    from airflow.providers.http.operators.http import SimpleHttpOperator
ImportError: cannot import name 'SimpleHttpOperator' from 'airflow.providers.http.operators.http' (/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/http/operators/http.py)
[2025-04-24T23:10:31.346+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2025-04-24T23:10:31.397+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/user_processing.py took 0.154 seconds
[2025-04-24T23:11:01.992+0000] {processor.py:186} INFO - Started process (PID=100) to work on /opt/airflow/dags/user_processing.py
[2025-04-24T23:11:01.995+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2025-04-24T23:11:02.003+0000] {logging_mixin.py:190} INFO - [2025-04-24T23:11:02.002+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2025-04-24T23:11:02.032+0000] {logging_mixin.py:190} INFO - [2025-04-24T23:11:02.023+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 4, in <module>
    from airflow.providers.http.operators.http import SimpleHttpOperator
ImportError: cannot import name 'SimpleHttpOperator' from 'airflow.providers.http.operators.http' (/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/http/operators/http.py)
[2025-04-24T23:11:02.037+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2025-04-24T23:11:02.061+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/user_processing.py took 0.077 seconds
[2025-04-24T23:11:32.610+0000] {processor.py:186} INFO - Started process (PID=108) to work on /opt/airflow/dags/user_processing.py
[2025-04-24T23:11:32.612+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2025-04-24T23:11:32.617+0000] {logging_mixin.py:190} INFO - [2025-04-24T23:11:32.617+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2025-04-24T23:11:32.658+0000] {logging_mixin.py:190} INFO - [2025-04-24T23:11:32.649+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 4, in <module>
    from airflow.providers.http.operators.http import SimpleHttpOperator
ImportError: cannot import name 'SimpleHttpOperator' from 'airflow.providers.http.operators.http' (/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/http/operators/http.py)
[2025-04-24T23:11:32.660+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2025-04-24T23:11:32.677+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/user_processing.py took 0.079 seconds
[2025-04-24T23:12:03.090+0000] {processor.py:186} INFO - Started process (PID=116) to work on /opt/airflow/dags/user_processing.py
[2025-04-24T23:12:03.092+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2025-04-24T23:12:03.094+0000] {logging_mixin.py:190} INFO - [2025-04-24T23:12:03.094+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2025-04-24T23:12:03.118+0000] {logging_mixin.py:190} INFO - [2025-04-24T23:12:03.114+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 4, in <module>
    from airflow.providers.http.operators.http import SimpleHttpOperator
ImportError: cannot import name 'SimpleHttpOperator' from 'airflow.providers.http.operators.http' (/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/http/operators/http.py)
[2025-04-24T23:12:03.121+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2025-04-24T23:12:03.140+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/user_processing.py took 0.056 seconds
[2025-04-24T23:12:33.592+0000] {processor.py:186} INFO - Started process (PID=124) to work on /opt/airflow/dags/user_processing.py
[2025-04-24T23:12:33.594+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2025-04-24T23:12:33.598+0000] {logging_mixin.py:190} INFO - [2025-04-24T23:12:33.597+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2025-04-24T23:12:33.637+0000] {logging_mixin.py:190} INFO - [2025-04-24T23:12:33.629+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 4, in <module>
    from airflow.providers.http.operators.http import SimpleHttpOperator
ImportError: cannot import name 'SimpleHttpOperator' from 'airflow.providers.http.operators.http' (/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/http/operators/http.py)
[2025-04-24T23:12:33.641+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2025-04-24T23:12:33.682+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/user_processing.py took 0.101 seconds
[2025-04-24T23:13:04.064+0000] {processor.py:186} INFO - Started process (PID=132) to work on /opt/airflow/dags/user_processing.py
[2025-04-24T23:13:04.065+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2025-04-24T23:13:04.072+0000] {logging_mixin.py:190} INFO - [2025-04-24T23:13:04.071+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2025-04-24T23:13:04.103+0000] {logging_mixin.py:190} INFO - [2025-04-24T23:13:04.096+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 4, in <module>
    from airflow.providers.http.operators.http import SimpleHttpOperator
ImportError: cannot import name 'SimpleHttpOperator' from 'airflow.providers.http.operators.http' (/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/http/operators/http.py)
[2025-04-24T23:13:04.107+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2025-04-24T23:13:04.127+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/user_processing.py took 0.072 seconds
[2025-04-24T23:13:34.505+0000] {processor.py:186} INFO - Started process (PID=140) to work on /opt/airflow/dags/user_processing.py
[2025-04-24T23:13:34.506+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2025-04-24T23:13:34.509+0000] {logging_mixin.py:190} INFO - [2025-04-24T23:13:34.509+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2025-04-24T23:13:34.536+0000] {logging_mixin.py:190} INFO - [2025-04-24T23:13:34.528+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 4, in <module>
    from airflow.providers.http.operators.http import SimpleHttpOperator
ImportError: cannot import name 'SimpleHttpOperator' from 'airflow.providers.http.operators.http' (/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/http/operators/http.py)
[2025-04-24T23:13:34.539+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2025-04-24T23:13:34.569+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/user_processing.py took 0.071 seconds
[2025-04-24T23:14:05.247+0000] {processor.py:186} INFO - Started process (PID=148) to work on /opt/airflow/dags/user_processing.py
[2025-04-24T23:14:05.249+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2025-04-24T23:14:05.255+0000] {logging_mixin.py:190} INFO - [2025-04-24T23:14:05.254+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2025-04-24T23:14:05.299+0000] {logging_mixin.py:190} INFO - [2025-04-24T23:14:05.287+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 4, in <module>
    from airflow.providers.http.operators.http import SimpleHttpOperator
ImportError: cannot import name 'SimpleHttpOperator' from 'airflow.providers.http.operators.http' (/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/http/operators/http.py)
[2025-04-24T23:14:05.307+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2025-04-24T23:14:05.352+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/user_processing.py took 0.115 seconds
[2025-04-24T23:14:36.029+0000] {processor.py:186} INFO - Started process (PID=156) to work on /opt/airflow/dags/user_processing.py
[2025-04-24T23:14:36.033+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2025-04-24T23:14:36.059+0000] {logging_mixin.py:190} INFO - [2025-04-24T23:14:36.058+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2025-04-24T23:14:36.341+0000] {logging_mixin.py:190} INFO - [2025-04-24T23:14:36.315+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 4, in <module>
    from airflow.providers.http.operators.http import SimpleHttpOperator
ImportError: cannot import name 'SimpleHttpOperator' from 'airflow.providers.http.operators.http' (/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/http/operators/http.py)
[2025-04-24T23:14:36.349+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2025-04-24T23:14:36.466+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/user_processing.py took 0.476 seconds
[2025-04-24T23:15:06.546+0000] {processor.py:186} INFO - Started process (PID=164) to work on /opt/airflow/dags/user_processing.py
[2025-04-24T23:15:06.548+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2025-04-24T23:15:06.550+0000] {logging_mixin.py:190} INFO - [2025-04-24T23:15:06.549+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2025-04-24T23:15:06.576+0000] {logging_mixin.py:190} INFO - [2025-04-24T23:15:06.567+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 4, in <module>
    from airflow.providers.http.operators.http import SimpleHttpOperator
ImportError: cannot import name 'SimpleHttpOperator' from 'airflow.providers.http.operators.http' (/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/http/operators/http.py)
[2025-04-24T23:15:06.578+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2025-04-24T23:15:06.604+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/user_processing.py took 0.065 seconds
[2025-04-24T23:15:37.209+0000] {processor.py:186} INFO - Started process (PID=172) to work on /opt/airflow/dags/user_processing.py
[2025-04-24T23:15:37.211+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2025-04-24T23:15:37.218+0000] {logging_mixin.py:190} INFO - [2025-04-24T23:15:37.218+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2025-04-24T23:15:37.265+0000] {logging_mixin.py:190} INFO - [2025-04-24T23:15:37.251+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 4, in <module>
    from airflow.providers.http.operators.http import SimpleHttpOperator
ImportError: cannot import name 'SimpleHttpOperator' from 'airflow.providers.http.operators.http' (/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/http/operators/http.py)
[2025-04-24T23:15:37.270+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2025-04-24T23:15:37.300+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/user_processing.py took 0.097 seconds
[2025-04-24T23:16:07.879+0000] {processor.py:186} INFO - Started process (PID=180) to work on /opt/airflow/dags/user_processing.py
[2025-04-24T23:16:07.880+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2025-04-24T23:16:07.890+0000] {logging_mixin.py:190} INFO - [2025-04-24T23:16:07.889+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2025-04-24T23:16:07.911+0000] {logging_mixin.py:190} INFO - [2025-04-24T23:16:07.905+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 4, in <module>
    from airflow.providers.http.operators.http import SimpleHttpOperator
ImportError: cannot import name 'SimpleHttpOperator' from 'airflow.providers.http.operators.http' (/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/http/operators/http.py)
[2025-04-24T23:16:07.914+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2025-04-24T23:16:07.937+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/user_processing.py took 0.063 seconds
[2025-04-24T23:16:38.387+0000] {processor.py:186} INFO - Started process (PID=188) to work on /opt/airflow/dags/user_processing.py
[2025-04-24T23:16:38.388+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2025-04-24T23:16:38.392+0000] {logging_mixin.py:190} INFO - [2025-04-24T23:16:38.391+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2025-04-24T23:16:38.410+0000] {logging_mixin.py:190} INFO - [2025-04-24T23:16:38.405+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 4, in <module>
    from airflow.providers.http.operators.http import SimpleHttpOperator
ImportError: cannot import name 'SimpleHttpOperator' from 'airflow.providers.http.operators.http' (/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/http/operators/http.py)
[2025-04-24T23:16:38.414+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2025-04-24T23:16:38.431+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/user_processing.py took 0.049 seconds
[2025-04-24T23:17:08.893+0000] {processor.py:186} INFO - Started process (PID=196) to work on /opt/airflow/dags/user_processing.py
[2025-04-24T23:17:08.894+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2025-04-24T23:17:08.901+0000] {logging_mixin.py:190} INFO - [2025-04-24T23:17:08.901+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2025-04-24T23:17:08.934+0000] {logging_mixin.py:190} INFO - [2025-04-24T23:17:08.919+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 4, in <module>
    from airflow.providers.http.operators.http import SimpleHttpOperator
ImportError: cannot import name 'SimpleHttpOperator' from 'airflow.providers.http.operators.http' (/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/http/operators/http.py)
[2025-04-24T23:17:08.938+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2025-04-24T23:17:08.961+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/user_processing.py took 0.074 seconds
[2025-04-24T23:17:39.452+0000] {processor.py:186} INFO - Started process (PID=204) to work on /opt/airflow/dags/user_processing.py
[2025-04-24T23:17:39.453+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2025-04-24T23:17:39.455+0000] {logging_mixin.py:190} INFO - [2025-04-24T23:17:39.455+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2025-04-24T23:17:39.476+0000] {logging_mixin.py:190} INFO - [2025-04-24T23:17:39.471+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 4, in <module>
    from airflow.providers.http.operators.http import SimpleHttpOperator
ImportError: cannot import name 'SimpleHttpOperator' from 'airflow.providers.http.operators.http' (/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/http/operators/http.py)
[2025-04-24T23:17:39.479+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2025-04-24T23:17:39.497+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/user_processing.py took 0.049 seconds
[2025-04-24T23:18:09.904+0000] {processor.py:186} INFO - Started process (PID=212) to work on /opt/airflow/dags/user_processing.py
[2025-04-24T23:18:09.906+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2025-04-24T23:18:09.908+0000] {logging_mixin.py:190} INFO - [2025-04-24T23:18:09.908+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2025-04-24T23:18:09.929+0000] {logging_mixin.py:190} INFO - [2025-04-24T23:18:09.924+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 4, in <module>
    from airflow.providers.http.operators.http import SimpleHttpOperator
ImportError: cannot import name 'SimpleHttpOperator' from 'airflow.providers.http.operators.http' (/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/http/operators/http.py)
[2025-04-24T23:18:09.931+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2025-04-24T23:18:09.945+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/user_processing.py took 0.046 seconds
[2025-04-24T23:18:40.371+0000] {processor.py:186} INFO - Started process (PID=220) to work on /opt/airflow/dags/user_processing.py
[2025-04-24T23:18:40.372+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2025-04-24T23:18:40.374+0000] {logging_mixin.py:190} INFO - [2025-04-24T23:18:40.374+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2025-04-24T23:18:40.400+0000] {logging_mixin.py:190} INFO - [2025-04-24T23:18:40.395+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 4, in <module>
    from airflow.providers.http.operators.http import SimpleHttpOperator
ImportError: cannot import name 'SimpleHttpOperator' from 'airflow.providers.http.operators.http' (/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/http/operators/http.py)
[2025-04-24T23:18:40.404+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2025-04-24T23:18:40.419+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/user_processing.py took 0.053 seconds
[2025-04-24T23:19:10.826+0000] {processor.py:186} INFO - Started process (PID=228) to work on /opt/airflow/dags/user_processing.py
[2025-04-24T23:19:10.828+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2025-04-24T23:19:10.830+0000] {logging_mixin.py:190} INFO - [2025-04-24T23:19:10.830+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2025-04-24T23:19:10.858+0000] {logging_mixin.py:190} INFO - [2025-04-24T23:19:10.852+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 4, in <module>
    from airflow.providers.http.operators.http import SimpleHttpOperator
ImportError: cannot import name 'SimpleHttpOperator' from 'airflow.providers.http.operators.http' (/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/http/operators/http.py)
[2025-04-24T23:19:10.861+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2025-04-24T23:19:10.877+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/user_processing.py took 0.057 seconds
[2025-04-24T23:19:41.356+0000] {processor.py:186} INFO - Started process (PID=236) to work on /opt/airflow/dags/user_processing.py
[2025-04-24T23:19:41.358+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2025-04-24T23:19:41.360+0000] {logging_mixin.py:190} INFO - [2025-04-24T23:19:41.360+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2025-04-24T23:19:41.381+0000] {logging_mixin.py:190} INFO - [2025-04-24T23:19:41.375+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 4, in <module>
    from airflow.providers.http.operators.http import SimpleHttpOperator
ImportError: cannot import name 'SimpleHttpOperator' from 'airflow.providers.http.operators.http' (/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/http/operators/http.py)
[2025-04-24T23:19:41.385+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2025-04-24T23:19:41.402+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/user_processing.py took 0.051 seconds
[2025-04-24T23:20:11.808+0000] {processor.py:186} INFO - Started process (PID=244) to work on /opt/airflow/dags/user_processing.py
[2025-04-24T23:20:11.809+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2025-04-24T23:20:11.812+0000] {logging_mixin.py:190} INFO - [2025-04-24T23:20:11.811+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2025-04-24T23:20:11.831+0000] {logging_mixin.py:190} INFO - [2025-04-24T23:20:11.825+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 4, in <module>
    from airflow.providers.http.operators.http import SimpleHttpOperator
ImportError: cannot import name 'SimpleHttpOperator' from 'airflow.providers.http.operators.http' (/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/http/operators/http.py)
[2025-04-24T23:20:11.834+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2025-04-24T23:20:11.853+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/user_processing.py took 0.049 seconds
[2025-04-24T23:20:42.253+0000] {processor.py:186} INFO - Started process (PID=252) to work on /opt/airflow/dags/user_processing.py
[2025-04-24T23:20:42.254+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2025-04-24T23:20:42.258+0000] {logging_mixin.py:190} INFO - [2025-04-24T23:20:42.257+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2025-04-24T23:20:42.287+0000] {logging_mixin.py:190} INFO - [2025-04-24T23:20:42.279+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 4, in <module>
    from airflow.providers.http.operators.http import SimpleHttpOperator
ImportError: cannot import name 'SimpleHttpOperator' from 'airflow.providers.http.operators.http' (/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/http/operators/http.py)
[2025-04-24T23:20:42.291+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2025-04-24T23:20:42.416+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/user_processing.py took 0.166 seconds
[2025-04-24T23:21:12.661+0000] {processor.py:186} INFO - Started process (PID=260) to work on /opt/airflow/dags/user_processing.py
[2025-04-24T23:21:12.666+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2025-04-24T23:21:12.670+0000] {logging_mixin.py:190} INFO - [2025-04-24T23:21:12.670+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2025-04-24T23:21:12.705+0000] {logging_mixin.py:190} INFO - [2025-04-24T23:21:12.700+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 4, in <module>
    from airflow.providers.http.operators.http import SimpleHttpOperator
ImportError: cannot import name 'SimpleHttpOperator' from 'airflow.providers.http.operators.http' (/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/http/operators/http.py)
[2025-04-24T23:21:12.708+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2025-04-24T23:21:12.726+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/user_processing.py took 0.070 seconds
[2025-04-24T23:21:43.134+0000] {processor.py:186} INFO - Started process (PID=268) to work on /opt/airflow/dags/user_processing.py
[2025-04-24T23:21:43.136+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2025-04-24T23:21:43.138+0000] {logging_mixin.py:190} INFO - [2025-04-24T23:21:43.138+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2025-04-24T23:21:43.158+0000] {logging_mixin.py:190} INFO - [2025-04-24T23:21:43.153+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 4, in <module>
    from airflow.providers.http.operators.http import SimpleHttpOperator
ImportError: cannot import name 'SimpleHttpOperator' from 'airflow.providers.http.operators.http' (/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/http/operators/http.py)
[2025-04-24T23:21:43.161+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2025-04-24T23:21:43.176+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/user_processing.py took 0.046 seconds
[2025-04-24T23:22:13.570+0000] {processor.py:186} INFO - Started process (PID=276) to work on /opt/airflow/dags/user_processing.py
[2025-04-24T23:22:13.571+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2025-04-24T23:22:13.574+0000] {logging_mixin.py:190} INFO - [2025-04-24T23:22:13.573+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2025-04-24T23:22:13.590+0000] {logging_mixin.py:190} INFO - [2025-04-24T23:22:13.586+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 4, in <module>
    from airflow.providers.http.operators.http import SimpleHttpOperator
ImportError: cannot import name 'SimpleHttpOperator' from 'airflow.providers.http.operators.http' (/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/http/operators/http.py)
[2025-04-24T23:22:13.592+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2025-04-24T23:22:13.607+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/user_processing.py took 0.042 seconds
[2025-04-24T23:22:43.987+0000] {processor.py:186} INFO - Started process (PID=284) to work on /opt/airflow/dags/user_processing.py
[2025-04-24T23:22:43.989+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2025-04-24T23:22:43.991+0000] {logging_mixin.py:190} INFO - [2025-04-24T23:22:43.990+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2025-04-24T23:22:44.016+0000] {logging_mixin.py:190} INFO - [2025-04-24T23:22:44.008+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 4, in <module>
    from airflow.providers.http.operators.http import SimpleHttpOperator
ImportError: cannot import name 'SimpleHttpOperator' from 'airflow.providers.http.operators.http' (/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/http/operators/http.py)
[2025-04-24T23:22:44.020+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2025-04-24T23:22:44.037+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/user_processing.py took 0.055 seconds
[2025-04-24T23:23:14.439+0000] {processor.py:186} INFO - Started process (PID=293) to work on /opt/airflow/dags/user_processing.py
[2025-04-24T23:23:14.440+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2025-04-24T23:23:14.441+0000] {logging_mixin.py:190} INFO - [2025-04-24T23:23:14.441+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2025-04-24T23:23:14.469+0000] {logging_mixin.py:190} INFO - [2025-04-24T23:23:14.458+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 4, in <module>
    from airflow.providers.http.operators.http import SimpleHttpOperator
ImportError: cannot import name 'SimpleHttpOperator' from 'airflow.providers.http.operators.http' (/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/http/operators/http.py)
[2025-04-24T23:23:14.473+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2025-04-24T23:23:14.496+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/user_processing.py took 0.062 seconds
[2025-04-24T23:23:44.930+0000] {processor.py:186} INFO - Started process (PID=301) to work on /opt/airflow/dags/user_processing.py
[2025-04-24T23:23:44.931+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2025-04-24T23:23:44.933+0000] {logging_mixin.py:190} INFO - [2025-04-24T23:23:44.933+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2025-04-24T23:23:44.964+0000] {logging_mixin.py:190} INFO - [2025-04-24T23:23:44.956+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 4, in <module>
    from airflow.providers.http.operators.http import SimpleHttpOperator
ImportError: cannot import name 'SimpleHttpOperator' from 'airflow.providers.http.operators.http' (/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/http/operators/http.py)
[2025-04-24T23:23:44.968+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2025-04-24T23:23:44.983+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/user_processing.py took 0.059 seconds
[2025-04-24T23:24:15.433+0000] {processor.py:186} INFO - Started process (PID=309) to work on /opt/airflow/dags/user_processing.py
[2025-04-24T23:24:15.435+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2025-04-24T23:24:15.443+0000] {logging_mixin.py:190} INFO - [2025-04-24T23:24:15.442+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2025-04-24T23:24:15.498+0000] {logging_mixin.py:190} INFO - [2025-04-24T23:24:15.485+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 4, in <module>
    from airflow.providers.http.operators.http import SimpleHttpOperator
ImportError: cannot import name 'SimpleHttpOperator' from 'airflow.providers.http.operators.http' (/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/http/operators/http.py)
[2025-04-24T23:24:15.501+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2025-04-24T23:24:15.521+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/user_processing.py took 0.106 seconds
[2025-04-24T23:24:45.896+0000] {processor.py:186} INFO - Started process (PID=317) to work on /opt/airflow/dags/user_processing.py
[2025-04-24T23:24:45.897+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2025-04-24T23:24:45.900+0000] {logging_mixin.py:190} INFO - [2025-04-24T23:24:45.899+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2025-04-24T23:24:45.923+0000] {logging_mixin.py:190} INFO - [2025-04-24T23:24:45.917+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 4, in <module>
    from airflow.providers.http.operators.http import SimpleHttpOperator
ImportError: cannot import name 'SimpleHttpOperator' from 'airflow.providers.http.operators.http' (/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/http/operators/http.py)
[2025-04-24T23:24:45.925+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2025-04-24T23:24:45.940+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/user_processing.py took 0.049 seconds
[2025-04-24T23:25:16.366+0000] {processor.py:186} INFO - Started process (PID=325) to work on /opt/airflow/dags/user_processing.py
[2025-04-24T23:25:16.369+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2025-04-24T23:25:16.376+0000] {logging_mixin.py:190} INFO - [2025-04-24T23:25:16.376+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2025-04-24T23:25:16.438+0000] {logging_mixin.py:190} INFO - [2025-04-24T23:25:16.428+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 4, in <module>
    from airflow.providers.http.operators.http import SimpleHttpOperator
ImportError: cannot import name 'SimpleHttpOperator' from 'airflow.providers.http.operators.http' (/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/http/operators/http.py)
[2025-04-24T23:25:16.442+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2025-04-24T23:25:16.462+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/user_processing.py took 0.113 seconds
[2025-04-24T23:25:46.845+0000] {processor.py:186} INFO - Started process (PID=333) to work on /opt/airflow/dags/user_processing.py
[2025-04-24T23:25:46.846+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2025-04-24T23:25:46.848+0000] {logging_mixin.py:190} INFO - [2025-04-24T23:25:46.848+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2025-04-24T23:25:46.880+0000] {logging_mixin.py:190} INFO - [2025-04-24T23:25:46.873+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 4, in <module>
    from airflow.providers.http.operators.http import SimpleHttpOperator
ImportError: cannot import name 'SimpleHttpOperator' from 'airflow.providers.http.operators.http' (/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/http/operators/http.py)
[2025-04-24T23:25:46.883+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2025-04-24T23:25:46.900+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/user_processing.py took 0.060 seconds
[2025-04-24T23:26:17.318+0000] {processor.py:186} INFO - Started process (PID=341) to work on /opt/airflow/dags/user_processing.py
[2025-04-24T23:26:17.320+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2025-04-24T23:26:17.322+0000] {logging_mixin.py:190} INFO - [2025-04-24T23:26:17.322+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2025-04-24T23:26:17.344+0000] {logging_mixin.py:190} INFO - [2025-04-24T23:26:17.340+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 4, in <module>
    from airflow.providers.http.operators.http import SimpleHttpOperator
ImportError: cannot import name 'SimpleHttpOperator' from 'airflow.providers.http.operators.http' (/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/http/operators/http.py)
[2025-04-24T23:26:17.347+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2025-04-24T23:26:17.362+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/user_processing.py took 0.051 seconds
[2025-04-24T23:26:47.739+0000] {processor.py:186} INFO - Started process (PID=349) to work on /opt/airflow/dags/user_processing.py
[2025-04-24T23:26:47.740+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2025-04-24T23:26:47.742+0000] {logging_mixin.py:190} INFO - [2025-04-24T23:26:47.742+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2025-04-24T23:26:47.767+0000] {logging_mixin.py:190} INFO - [2025-04-24T23:26:47.758+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 4, in <module>
    from airflow.providers.http.operators.http import SimpleHttpOperator
ImportError: cannot import name 'SimpleHttpOperator' from 'airflow.providers.http.operators.http' (/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/http/operators/http.py)
[2025-04-24T23:26:47.771+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2025-04-24T23:26:47.788+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/user_processing.py took 0.055 seconds
[2025-04-24T23:27:18.223+0000] {processor.py:186} INFO - Started process (PID=357) to work on /opt/airflow/dags/user_processing.py
[2025-04-24T23:27:18.225+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2025-04-24T23:27:18.228+0000] {logging_mixin.py:190} INFO - [2025-04-24T23:27:18.228+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2025-04-24T23:27:18.253+0000] {logging_mixin.py:190} INFO - [2025-04-24T23:27:18.247+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 4, in <module>
    from airflow.providers.http.operators.http import SimpleHttpOperator
ImportError: cannot import name 'SimpleHttpOperator' from 'airflow.providers.http.operators.http' (/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/http/operators/http.py)
[2025-04-24T23:27:18.257+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2025-04-24T23:27:18.275+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/user_processing.py took 0.059 seconds
[2025-04-24T23:27:48.711+0000] {processor.py:186} INFO - Started process (PID=365) to work on /opt/airflow/dags/user_processing.py
[2025-04-24T23:27:48.714+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2025-04-24T23:27:48.719+0000] {logging_mixin.py:190} INFO - [2025-04-24T23:27:48.719+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2025-04-24T23:27:48.762+0000] {logging_mixin.py:190} INFO - [2025-04-24T23:27:48.751+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 4, in <module>
    from airflow.providers.http.operators.http import SimpleHttpOperator
ImportError: cannot import name 'SimpleHttpOperator' from 'airflow.providers.http.operators.http' (/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/http/operators/http.py)
[2025-04-24T23:27:48.769+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2025-04-24T23:27:48.786+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/user_processing.py took 0.082 seconds
[2025-04-24T23:28:19.216+0000] {processor.py:186} INFO - Started process (PID=373) to work on /opt/airflow/dags/user_processing.py
[2025-04-24T23:28:19.217+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2025-04-24T23:28:19.220+0000] {logging_mixin.py:190} INFO - [2025-04-24T23:28:19.220+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2025-04-24T23:28:19.245+0000] {logging_mixin.py:190} INFO - [2025-04-24T23:28:19.238+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 4, in <module>
    from airflow.providers.http.operators.http import SimpleHttpOperator
ImportError: cannot import name 'SimpleHttpOperator' from 'airflow.providers.http.operators.http' (/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/http/operators/http.py)
[2025-04-24T23:28:19.251+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2025-04-24T23:28:19.267+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/user_processing.py took 0.058 seconds
[2025-04-24T23:28:49.677+0000] {processor.py:186} INFO - Started process (PID=380) to work on /opt/airflow/dags/user_processing.py
[2025-04-24T23:28:49.678+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2025-04-24T23:28:49.682+0000] {logging_mixin.py:190} INFO - [2025-04-24T23:28:49.682+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2025-04-24T23:28:49.714+0000] {logging_mixin.py:190} INFO - [2025-04-24T23:28:49.705+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 4, in <module>
    from airflow.providers.http.operators.http import SimpleHttpOperator
ImportError: cannot import name 'SimpleHttpOperator' from 'airflow.providers.http.operators.http' (/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/http/operators/http.py)
[2025-04-24T23:28:49.720+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2025-04-24T23:28:49.752+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/user_processing.py took 0.086 seconds
[2025-04-24T23:29:20.139+0000] {processor.py:186} INFO - Started process (PID=388) to work on /opt/airflow/dags/user_processing.py
[2025-04-24T23:29:20.140+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2025-04-24T23:29:20.143+0000] {logging_mixin.py:190} INFO - [2025-04-24T23:29:20.142+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2025-04-24T23:29:20.165+0000] {logging_mixin.py:190} INFO - [2025-04-24T23:29:20.159+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 4, in <module>
    from airflow.providers.http.operators.http import SimpleHttpOperator
ImportError: cannot import name 'SimpleHttpOperator' from 'airflow.providers.http.operators.http' (/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/http/operators/http.py)
[2025-04-24T23:29:20.168+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2025-04-24T23:29:20.183+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/user_processing.py took 0.050 seconds
[2025-04-24T23:29:50.692+0000] {processor.py:186} INFO - Started process (PID=397) to work on /opt/airflow/dags/user_processing.py
[2025-04-24T23:29:50.694+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2025-04-24T23:29:50.697+0000] {logging_mixin.py:190} INFO - [2025-04-24T23:29:50.697+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2025-04-24T23:29:50.726+0000] {logging_mixin.py:190} INFO - [2025-04-24T23:29:50.719+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 4, in <module>
    from airflow.providers.http.operators.http import SimpleHttpOperator
ImportError: cannot import name 'SimpleHttpOperator' from 'airflow.providers.http.operators.http' (/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/http/operators/http.py)
[2025-04-24T23:29:50.729+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2025-04-24T23:29:50.749+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/user_processing.py took 0.064 seconds
[2025-04-24T23:30:21.202+0000] {processor.py:186} INFO - Started process (PID=405) to work on /opt/airflow/dags/user_processing.py
[2025-04-24T23:30:21.203+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2025-04-24T23:30:21.206+0000] {logging_mixin.py:190} INFO - [2025-04-24T23:30:21.206+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2025-04-24T23:30:21.229+0000] {logging_mixin.py:190} INFO - [2025-04-24T23:30:21.223+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 4, in <module>
    from airflow.providers.http.operators.http import SimpleHttpOperator
ImportError: cannot import name 'SimpleHttpOperator' from 'airflow.providers.http.operators.http' (/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/http/operators/http.py)
[2025-04-24T23:30:21.232+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2025-04-24T23:30:21.248+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/user_processing.py took 0.050 seconds
