[2025-04-24T23:09:29.750+0000] {processor.py:186} INFO - Started process (PID=75) to work on /opt/airflow/dags/user_processing.py
[2025-04-24T23:09:29.753+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2025-04-24T23:09:29.762+0000] {logging_mixin.py:190} INFO - [2025-04-24T23:09:29.761+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2025-04-24T23:09:30.070+0000] {logging_mixin.py:190} INFO - [2025-04-24T23:09:29.962+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 4, in <module>
    from airflow.providers.http.operators.http import SimpleHttpOperator
ImportError: cannot import name 'SimpleHttpOperator' from 'airflow.providers.http.operators.http' (/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/http/operators/http.py)
[2025-04-24T23:09:30.090+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2025-04-24T23:09:30.158+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/user_processing.py took 0.424 seconds
[2025-04-24T23:10:00.351+0000] {processor.py:186} INFO - Started process (PID=84) to work on /opt/airflow/dags/user_processing.py
[2025-04-24T23:10:00.352+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2025-04-24T23:10:00.356+0000] {logging_mixin.py:190} INFO - [2025-04-24T23:10:00.355+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2025-04-24T23:10:00.418+0000] {logging_mixin.py:190} INFO - [2025-04-24T23:10:00.403+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 4, in <module>
    from airflow.providers.http.operators.http import SimpleHttpOperator
ImportError: cannot import name 'SimpleHttpOperator' from 'airflow.providers.http.operators.http' (/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/http/operators/http.py)
[2025-04-24T23:10:00.434+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2025-04-24T23:10:00.498+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/user_processing.py took 0.157 seconds
[2025-04-24T23:10:31.266+0000] {processor.py:186} INFO - Started process (PID=92) to work on /opt/airflow/dags/user_processing.py
[2025-04-24T23:10:31.279+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2025-04-24T23:10:31.289+0000] {logging_mixin.py:190} INFO - [2025-04-24T23:10:31.288+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2025-04-24T23:10:31.341+0000] {logging_mixin.py:190} INFO - [2025-04-24T23:10:31.327+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 4, in <module>
    from airflow.providers.http.operators.http import SimpleHttpOperator
ImportError: cannot import name 'SimpleHttpOperator' from 'airflow.providers.http.operators.http' (/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/http/operators/http.py)
[2025-04-24T23:10:31.346+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2025-04-24T23:10:31.397+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/user_processing.py took 0.154 seconds
[2025-04-24T23:11:01.992+0000] {processor.py:186} INFO - Started process (PID=100) to work on /opt/airflow/dags/user_processing.py
[2025-04-24T23:11:01.995+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2025-04-24T23:11:02.003+0000] {logging_mixin.py:190} INFO - [2025-04-24T23:11:02.002+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2025-04-24T23:11:02.032+0000] {logging_mixin.py:190} INFO - [2025-04-24T23:11:02.023+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 4, in <module>
    from airflow.providers.http.operators.http import SimpleHttpOperator
ImportError: cannot import name 'SimpleHttpOperator' from 'airflow.providers.http.operators.http' (/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/http/operators/http.py)
[2025-04-24T23:11:02.037+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2025-04-24T23:11:02.061+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/user_processing.py took 0.077 seconds
[2025-04-24T23:11:32.610+0000] {processor.py:186} INFO - Started process (PID=108) to work on /opt/airflow/dags/user_processing.py
[2025-04-24T23:11:32.612+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2025-04-24T23:11:32.617+0000] {logging_mixin.py:190} INFO - [2025-04-24T23:11:32.617+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2025-04-24T23:11:32.658+0000] {logging_mixin.py:190} INFO - [2025-04-24T23:11:32.649+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 4, in <module>
    from airflow.providers.http.operators.http import SimpleHttpOperator
ImportError: cannot import name 'SimpleHttpOperator' from 'airflow.providers.http.operators.http' (/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/http/operators/http.py)
[2025-04-24T23:11:32.660+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2025-04-24T23:11:32.677+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/user_processing.py took 0.079 seconds
[2025-04-24T23:12:03.090+0000] {processor.py:186} INFO - Started process (PID=116) to work on /opt/airflow/dags/user_processing.py
[2025-04-24T23:12:03.092+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2025-04-24T23:12:03.094+0000] {logging_mixin.py:190} INFO - [2025-04-24T23:12:03.094+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2025-04-24T23:12:03.118+0000] {logging_mixin.py:190} INFO - [2025-04-24T23:12:03.114+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 4, in <module>
    from airflow.providers.http.operators.http import SimpleHttpOperator
ImportError: cannot import name 'SimpleHttpOperator' from 'airflow.providers.http.operators.http' (/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/http/operators/http.py)
[2025-04-24T23:12:03.121+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2025-04-24T23:12:03.140+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/user_processing.py took 0.056 seconds
[2025-04-24T23:12:33.592+0000] {processor.py:186} INFO - Started process (PID=124) to work on /opt/airflow/dags/user_processing.py
[2025-04-24T23:12:33.594+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2025-04-24T23:12:33.598+0000] {logging_mixin.py:190} INFO - [2025-04-24T23:12:33.597+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2025-04-24T23:12:33.637+0000] {logging_mixin.py:190} INFO - [2025-04-24T23:12:33.629+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 4, in <module>
    from airflow.providers.http.operators.http import SimpleHttpOperator
ImportError: cannot import name 'SimpleHttpOperator' from 'airflow.providers.http.operators.http' (/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/http/operators/http.py)
[2025-04-24T23:12:33.641+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2025-04-24T23:12:33.682+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/user_processing.py took 0.101 seconds
[2025-04-24T23:13:04.064+0000] {processor.py:186} INFO - Started process (PID=132) to work on /opt/airflow/dags/user_processing.py
[2025-04-24T23:13:04.065+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2025-04-24T23:13:04.072+0000] {logging_mixin.py:190} INFO - [2025-04-24T23:13:04.071+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2025-04-24T23:13:04.103+0000] {logging_mixin.py:190} INFO - [2025-04-24T23:13:04.096+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 4, in <module>
    from airflow.providers.http.operators.http import SimpleHttpOperator
ImportError: cannot import name 'SimpleHttpOperator' from 'airflow.providers.http.operators.http' (/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/http/operators/http.py)
[2025-04-24T23:13:04.107+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2025-04-24T23:13:04.127+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/user_processing.py took 0.072 seconds
[2025-04-24T23:13:34.505+0000] {processor.py:186} INFO - Started process (PID=140) to work on /opt/airflow/dags/user_processing.py
[2025-04-24T23:13:34.506+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2025-04-24T23:13:34.509+0000] {logging_mixin.py:190} INFO - [2025-04-24T23:13:34.509+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2025-04-24T23:13:34.536+0000] {logging_mixin.py:190} INFO - [2025-04-24T23:13:34.528+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 4, in <module>
    from airflow.providers.http.operators.http import SimpleHttpOperator
ImportError: cannot import name 'SimpleHttpOperator' from 'airflow.providers.http.operators.http' (/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/http/operators/http.py)
[2025-04-24T23:13:34.539+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2025-04-24T23:13:34.569+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/user_processing.py took 0.071 seconds
[2025-04-24T23:14:05.247+0000] {processor.py:186} INFO - Started process (PID=148) to work on /opt/airflow/dags/user_processing.py
[2025-04-24T23:14:05.249+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2025-04-24T23:14:05.255+0000] {logging_mixin.py:190} INFO - [2025-04-24T23:14:05.254+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2025-04-24T23:14:05.299+0000] {logging_mixin.py:190} INFO - [2025-04-24T23:14:05.287+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 4, in <module>
    from airflow.providers.http.operators.http import SimpleHttpOperator
ImportError: cannot import name 'SimpleHttpOperator' from 'airflow.providers.http.operators.http' (/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/http/operators/http.py)
[2025-04-24T23:14:05.307+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2025-04-24T23:14:05.352+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/user_processing.py took 0.115 seconds
[2025-04-24T23:14:36.029+0000] {processor.py:186} INFO - Started process (PID=156) to work on /opt/airflow/dags/user_processing.py
[2025-04-24T23:14:36.033+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2025-04-24T23:14:36.059+0000] {logging_mixin.py:190} INFO - [2025-04-24T23:14:36.058+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2025-04-24T23:14:36.341+0000] {logging_mixin.py:190} INFO - [2025-04-24T23:14:36.315+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 4, in <module>
    from airflow.providers.http.operators.http import SimpleHttpOperator
ImportError: cannot import name 'SimpleHttpOperator' from 'airflow.providers.http.operators.http' (/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/http/operators/http.py)
[2025-04-24T23:14:36.349+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2025-04-24T23:14:36.466+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/user_processing.py took 0.476 seconds
[2025-04-24T23:15:06.546+0000] {processor.py:186} INFO - Started process (PID=164) to work on /opt/airflow/dags/user_processing.py
[2025-04-24T23:15:06.548+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2025-04-24T23:15:06.550+0000] {logging_mixin.py:190} INFO - [2025-04-24T23:15:06.549+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2025-04-24T23:15:06.576+0000] {logging_mixin.py:190} INFO - [2025-04-24T23:15:06.567+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 4, in <module>
    from airflow.providers.http.operators.http import SimpleHttpOperator
ImportError: cannot import name 'SimpleHttpOperator' from 'airflow.providers.http.operators.http' (/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/http/operators/http.py)
[2025-04-24T23:15:06.578+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2025-04-24T23:15:06.604+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/user_processing.py took 0.065 seconds
[2025-04-24T23:15:37.209+0000] {processor.py:186} INFO - Started process (PID=172) to work on /opt/airflow/dags/user_processing.py
[2025-04-24T23:15:37.211+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2025-04-24T23:15:37.218+0000] {logging_mixin.py:190} INFO - [2025-04-24T23:15:37.218+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2025-04-24T23:15:37.265+0000] {logging_mixin.py:190} INFO - [2025-04-24T23:15:37.251+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 4, in <module>
    from airflow.providers.http.operators.http import SimpleHttpOperator
ImportError: cannot import name 'SimpleHttpOperator' from 'airflow.providers.http.operators.http' (/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/http/operators/http.py)
[2025-04-24T23:15:37.270+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2025-04-24T23:15:37.300+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/user_processing.py took 0.097 seconds
[2025-04-24T23:16:07.879+0000] {processor.py:186} INFO - Started process (PID=180) to work on /opt/airflow/dags/user_processing.py
[2025-04-24T23:16:07.880+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2025-04-24T23:16:07.890+0000] {logging_mixin.py:190} INFO - [2025-04-24T23:16:07.889+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2025-04-24T23:16:07.911+0000] {logging_mixin.py:190} INFO - [2025-04-24T23:16:07.905+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 4, in <module>
    from airflow.providers.http.operators.http import SimpleHttpOperator
ImportError: cannot import name 'SimpleHttpOperator' from 'airflow.providers.http.operators.http' (/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/http/operators/http.py)
[2025-04-24T23:16:07.914+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2025-04-24T23:16:07.937+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/user_processing.py took 0.063 seconds
[2025-04-24T23:16:38.387+0000] {processor.py:186} INFO - Started process (PID=188) to work on /opt/airflow/dags/user_processing.py
[2025-04-24T23:16:38.388+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2025-04-24T23:16:38.392+0000] {logging_mixin.py:190} INFO - [2025-04-24T23:16:38.391+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2025-04-24T23:16:38.410+0000] {logging_mixin.py:190} INFO - [2025-04-24T23:16:38.405+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 4, in <module>
    from airflow.providers.http.operators.http import SimpleHttpOperator
ImportError: cannot import name 'SimpleHttpOperator' from 'airflow.providers.http.operators.http' (/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/http/operators/http.py)
[2025-04-24T23:16:38.414+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2025-04-24T23:16:38.431+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/user_processing.py took 0.049 seconds
[2025-04-24T23:17:08.893+0000] {processor.py:186} INFO - Started process (PID=196) to work on /opt/airflow/dags/user_processing.py
[2025-04-24T23:17:08.894+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2025-04-24T23:17:08.901+0000] {logging_mixin.py:190} INFO - [2025-04-24T23:17:08.901+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2025-04-24T23:17:08.934+0000] {logging_mixin.py:190} INFO - [2025-04-24T23:17:08.919+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 4, in <module>
    from airflow.providers.http.operators.http import SimpleHttpOperator
ImportError: cannot import name 'SimpleHttpOperator' from 'airflow.providers.http.operators.http' (/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/http/operators/http.py)
[2025-04-24T23:17:08.938+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2025-04-24T23:17:08.961+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/user_processing.py took 0.074 seconds
[2025-04-24T23:17:39.452+0000] {processor.py:186} INFO - Started process (PID=204) to work on /opt/airflow/dags/user_processing.py
[2025-04-24T23:17:39.453+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2025-04-24T23:17:39.455+0000] {logging_mixin.py:190} INFO - [2025-04-24T23:17:39.455+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2025-04-24T23:17:39.476+0000] {logging_mixin.py:190} INFO - [2025-04-24T23:17:39.471+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 4, in <module>
    from airflow.providers.http.operators.http import SimpleHttpOperator
ImportError: cannot import name 'SimpleHttpOperator' from 'airflow.providers.http.operators.http' (/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/http/operators/http.py)
[2025-04-24T23:17:39.479+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2025-04-24T23:17:39.497+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/user_processing.py took 0.049 seconds
[2025-04-24T23:18:09.904+0000] {processor.py:186} INFO - Started process (PID=212) to work on /opt/airflow/dags/user_processing.py
[2025-04-24T23:18:09.906+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2025-04-24T23:18:09.908+0000] {logging_mixin.py:190} INFO - [2025-04-24T23:18:09.908+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2025-04-24T23:18:09.929+0000] {logging_mixin.py:190} INFO - [2025-04-24T23:18:09.924+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 4, in <module>
    from airflow.providers.http.operators.http import SimpleHttpOperator
ImportError: cannot import name 'SimpleHttpOperator' from 'airflow.providers.http.operators.http' (/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/http/operators/http.py)
[2025-04-24T23:18:09.931+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2025-04-24T23:18:09.945+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/user_processing.py took 0.046 seconds
[2025-04-24T23:18:40.371+0000] {processor.py:186} INFO - Started process (PID=220) to work on /opt/airflow/dags/user_processing.py
[2025-04-24T23:18:40.372+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2025-04-24T23:18:40.374+0000] {logging_mixin.py:190} INFO - [2025-04-24T23:18:40.374+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2025-04-24T23:18:40.400+0000] {logging_mixin.py:190} INFO - [2025-04-24T23:18:40.395+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 4, in <module>
    from airflow.providers.http.operators.http import SimpleHttpOperator
ImportError: cannot import name 'SimpleHttpOperator' from 'airflow.providers.http.operators.http' (/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/http/operators/http.py)
[2025-04-24T23:18:40.404+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2025-04-24T23:18:40.419+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/user_processing.py took 0.053 seconds
[2025-04-24T23:19:10.826+0000] {processor.py:186} INFO - Started process (PID=228) to work on /opt/airflow/dags/user_processing.py
[2025-04-24T23:19:10.828+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2025-04-24T23:19:10.830+0000] {logging_mixin.py:190} INFO - [2025-04-24T23:19:10.830+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2025-04-24T23:19:10.858+0000] {logging_mixin.py:190} INFO - [2025-04-24T23:19:10.852+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 4, in <module>
    from airflow.providers.http.operators.http import SimpleHttpOperator
ImportError: cannot import name 'SimpleHttpOperator' from 'airflow.providers.http.operators.http' (/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/http/operators/http.py)
[2025-04-24T23:19:10.861+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2025-04-24T23:19:10.877+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/user_processing.py took 0.057 seconds
[2025-04-24T23:19:41.356+0000] {processor.py:186} INFO - Started process (PID=236) to work on /opt/airflow/dags/user_processing.py
[2025-04-24T23:19:41.358+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2025-04-24T23:19:41.360+0000] {logging_mixin.py:190} INFO - [2025-04-24T23:19:41.360+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2025-04-24T23:19:41.381+0000] {logging_mixin.py:190} INFO - [2025-04-24T23:19:41.375+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 4, in <module>
    from airflow.providers.http.operators.http import SimpleHttpOperator
ImportError: cannot import name 'SimpleHttpOperator' from 'airflow.providers.http.operators.http' (/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/http/operators/http.py)
[2025-04-24T23:19:41.385+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2025-04-24T23:19:41.402+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/user_processing.py took 0.051 seconds
[2025-04-24T23:20:11.808+0000] {processor.py:186} INFO - Started process (PID=244) to work on /opt/airflow/dags/user_processing.py
[2025-04-24T23:20:11.809+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2025-04-24T23:20:11.812+0000] {logging_mixin.py:190} INFO - [2025-04-24T23:20:11.811+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2025-04-24T23:20:11.831+0000] {logging_mixin.py:190} INFO - [2025-04-24T23:20:11.825+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 4, in <module>
    from airflow.providers.http.operators.http import SimpleHttpOperator
ImportError: cannot import name 'SimpleHttpOperator' from 'airflow.providers.http.operators.http' (/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/http/operators/http.py)
[2025-04-24T23:20:11.834+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2025-04-24T23:20:11.853+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/user_processing.py took 0.049 seconds
[2025-04-24T23:20:42.253+0000] {processor.py:186} INFO - Started process (PID=252) to work on /opt/airflow/dags/user_processing.py
[2025-04-24T23:20:42.254+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2025-04-24T23:20:42.258+0000] {logging_mixin.py:190} INFO - [2025-04-24T23:20:42.257+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2025-04-24T23:20:42.287+0000] {logging_mixin.py:190} INFO - [2025-04-24T23:20:42.279+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 4, in <module>
    from airflow.providers.http.operators.http import SimpleHttpOperator
ImportError: cannot import name 'SimpleHttpOperator' from 'airflow.providers.http.operators.http' (/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/http/operators/http.py)
[2025-04-24T23:20:42.291+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2025-04-24T23:20:42.416+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/user_processing.py took 0.166 seconds
[2025-04-24T23:21:12.661+0000] {processor.py:186} INFO - Started process (PID=260) to work on /opt/airflow/dags/user_processing.py
[2025-04-24T23:21:12.666+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2025-04-24T23:21:12.670+0000] {logging_mixin.py:190} INFO - [2025-04-24T23:21:12.670+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2025-04-24T23:21:12.705+0000] {logging_mixin.py:190} INFO - [2025-04-24T23:21:12.700+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 4, in <module>
    from airflow.providers.http.operators.http import SimpleHttpOperator
ImportError: cannot import name 'SimpleHttpOperator' from 'airflow.providers.http.operators.http' (/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/http/operators/http.py)
[2025-04-24T23:21:12.708+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2025-04-24T23:21:12.726+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/user_processing.py took 0.070 seconds
[2025-04-24T23:21:43.134+0000] {processor.py:186} INFO - Started process (PID=268) to work on /opt/airflow/dags/user_processing.py
[2025-04-24T23:21:43.136+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2025-04-24T23:21:43.138+0000] {logging_mixin.py:190} INFO - [2025-04-24T23:21:43.138+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2025-04-24T23:21:43.158+0000] {logging_mixin.py:190} INFO - [2025-04-24T23:21:43.153+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 4, in <module>
    from airflow.providers.http.operators.http import SimpleHttpOperator
ImportError: cannot import name 'SimpleHttpOperator' from 'airflow.providers.http.operators.http' (/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/http/operators/http.py)
[2025-04-24T23:21:43.161+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2025-04-24T23:21:43.176+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/user_processing.py took 0.046 seconds
[2025-04-24T23:22:13.570+0000] {processor.py:186} INFO - Started process (PID=276) to work on /opt/airflow/dags/user_processing.py
[2025-04-24T23:22:13.571+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2025-04-24T23:22:13.574+0000] {logging_mixin.py:190} INFO - [2025-04-24T23:22:13.573+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2025-04-24T23:22:13.590+0000] {logging_mixin.py:190} INFO - [2025-04-24T23:22:13.586+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 4, in <module>
    from airflow.providers.http.operators.http import SimpleHttpOperator
ImportError: cannot import name 'SimpleHttpOperator' from 'airflow.providers.http.operators.http' (/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/http/operators/http.py)
[2025-04-24T23:22:13.592+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2025-04-24T23:22:13.607+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/user_processing.py took 0.042 seconds
[2025-04-24T23:22:43.987+0000] {processor.py:186} INFO - Started process (PID=284) to work on /opt/airflow/dags/user_processing.py
[2025-04-24T23:22:43.989+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2025-04-24T23:22:43.991+0000] {logging_mixin.py:190} INFO - [2025-04-24T23:22:43.990+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2025-04-24T23:22:44.016+0000] {logging_mixin.py:190} INFO - [2025-04-24T23:22:44.008+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 4, in <module>
    from airflow.providers.http.operators.http import SimpleHttpOperator
ImportError: cannot import name 'SimpleHttpOperator' from 'airflow.providers.http.operators.http' (/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/http/operators/http.py)
[2025-04-24T23:22:44.020+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2025-04-24T23:22:44.037+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/user_processing.py took 0.055 seconds
[2025-04-24T23:23:14.439+0000] {processor.py:186} INFO - Started process (PID=293) to work on /opt/airflow/dags/user_processing.py
[2025-04-24T23:23:14.440+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2025-04-24T23:23:14.441+0000] {logging_mixin.py:190} INFO - [2025-04-24T23:23:14.441+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2025-04-24T23:23:14.469+0000] {logging_mixin.py:190} INFO - [2025-04-24T23:23:14.458+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 4, in <module>
    from airflow.providers.http.operators.http import SimpleHttpOperator
ImportError: cannot import name 'SimpleHttpOperator' from 'airflow.providers.http.operators.http' (/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/http/operators/http.py)
[2025-04-24T23:23:14.473+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2025-04-24T23:23:14.496+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/user_processing.py took 0.062 seconds
[2025-04-24T23:23:44.930+0000] {processor.py:186} INFO - Started process (PID=301) to work on /opt/airflow/dags/user_processing.py
[2025-04-24T23:23:44.931+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2025-04-24T23:23:44.933+0000] {logging_mixin.py:190} INFO - [2025-04-24T23:23:44.933+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2025-04-24T23:23:44.964+0000] {logging_mixin.py:190} INFO - [2025-04-24T23:23:44.956+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 4, in <module>
    from airflow.providers.http.operators.http import SimpleHttpOperator
ImportError: cannot import name 'SimpleHttpOperator' from 'airflow.providers.http.operators.http' (/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/http/operators/http.py)
[2025-04-24T23:23:44.968+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2025-04-24T23:23:44.983+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/user_processing.py took 0.059 seconds
[2025-04-24T23:24:15.433+0000] {processor.py:186} INFO - Started process (PID=309) to work on /opt/airflow/dags/user_processing.py
[2025-04-24T23:24:15.435+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2025-04-24T23:24:15.443+0000] {logging_mixin.py:190} INFO - [2025-04-24T23:24:15.442+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2025-04-24T23:24:15.498+0000] {logging_mixin.py:190} INFO - [2025-04-24T23:24:15.485+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 4, in <module>
    from airflow.providers.http.operators.http import SimpleHttpOperator
ImportError: cannot import name 'SimpleHttpOperator' from 'airflow.providers.http.operators.http' (/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/http/operators/http.py)
[2025-04-24T23:24:15.501+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2025-04-24T23:24:15.521+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/user_processing.py took 0.106 seconds
[2025-04-24T23:24:45.896+0000] {processor.py:186} INFO - Started process (PID=317) to work on /opt/airflow/dags/user_processing.py
[2025-04-24T23:24:45.897+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2025-04-24T23:24:45.900+0000] {logging_mixin.py:190} INFO - [2025-04-24T23:24:45.899+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2025-04-24T23:24:45.923+0000] {logging_mixin.py:190} INFO - [2025-04-24T23:24:45.917+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 4, in <module>
    from airflow.providers.http.operators.http import SimpleHttpOperator
ImportError: cannot import name 'SimpleHttpOperator' from 'airflow.providers.http.operators.http' (/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/http/operators/http.py)
[2025-04-24T23:24:45.925+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2025-04-24T23:24:45.940+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/user_processing.py took 0.049 seconds
[2025-04-24T23:25:16.366+0000] {processor.py:186} INFO - Started process (PID=325) to work on /opt/airflow/dags/user_processing.py
[2025-04-24T23:25:16.369+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2025-04-24T23:25:16.376+0000] {logging_mixin.py:190} INFO - [2025-04-24T23:25:16.376+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2025-04-24T23:25:16.438+0000] {logging_mixin.py:190} INFO - [2025-04-24T23:25:16.428+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 4, in <module>
    from airflow.providers.http.operators.http import SimpleHttpOperator
ImportError: cannot import name 'SimpleHttpOperator' from 'airflow.providers.http.operators.http' (/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/http/operators/http.py)
[2025-04-24T23:25:16.442+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2025-04-24T23:25:16.462+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/user_processing.py took 0.113 seconds
[2025-04-24T23:25:46.845+0000] {processor.py:186} INFO - Started process (PID=333) to work on /opt/airflow/dags/user_processing.py
[2025-04-24T23:25:46.846+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2025-04-24T23:25:46.848+0000] {logging_mixin.py:190} INFO - [2025-04-24T23:25:46.848+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2025-04-24T23:25:46.880+0000] {logging_mixin.py:190} INFO - [2025-04-24T23:25:46.873+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 4, in <module>
    from airflow.providers.http.operators.http import SimpleHttpOperator
ImportError: cannot import name 'SimpleHttpOperator' from 'airflow.providers.http.operators.http' (/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/http/operators/http.py)
[2025-04-24T23:25:46.883+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2025-04-24T23:25:46.900+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/user_processing.py took 0.060 seconds
[2025-04-24T23:26:17.318+0000] {processor.py:186} INFO - Started process (PID=341) to work on /opt/airflow/dags/user_processing.py
[2025-04-24T23:26:17.320+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2025-04-24T23:26:17.322+0000] {logging_mixin.py:190} INFO - [2025-04-24T23:26:17.322+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2025-04-24T23:26:17.344+0000] {logging_mixin.py:190} INFO - [2025-04-24T23:26:17.340+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 4, in <module>
    from airflow.providers.http.operators.http import SimpleHttpOperator
ImportError: cannot import name 'SimpleHttpOperator' from 'airflow.providers.http.operators.http' (/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/http/operators/http.py)
[2025-04-24T23:26:17.347+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2025-04-24T23:26:17.362+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/user_processing.py took 0.051 seconds
[2025-04-24T23:26:47.739+0000] {processor.py:186} INFO - Started process (PID=349) to work on /opt/airflow/dags/user_processing.py
[2025-04-24T23:26:47.740+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2025-04-24T23:26:47.742+0000] {logging_mixin.py:190} INFO - [2025-04-24T23:26:47.742+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2025-04-24T23:26:47.767+0000] {logging_mixin.py:190} INFO - [2025-04-24T23:26:47.758+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 4, in <module>
    from airflow.providers.http.operators.http import SimpleHttpOperator
ImportError: cannot import name 'SimpleHttpOperator' from 'airflow.providers.http.operators.http' (/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/http/operators/http.py)
[2025-04-24T23:26:47.771+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2025-04-24T23:26:47.788+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/user_processing.py took 0.055 seconds
[2025-04-24T23:27:18.223+0000] {processor.py:186} INFO - Started process (PID=357) to work on /opt/airflow/dags/user_processing.py
[2025-04-24T23:27:18.225+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2025-04-24T23:27:18.228+0000] {logging_mixin.py:190} INFO - [2025-04-24T23:27:18.228+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2025-04-24T23:27:18.253+0000] {logging_mixin.py:190} INFO - [2025-04-24T23:27:18.247+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 4, in <module>
    from airflow.providers.http.operators.http import SimpleHttpOperator
ImportError: cannot import name 'SimpleHttpOperator' from 'airflow.providers.http.operators.http' (/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/http/operators/http.py)
[2025-04-24T23:27:18.257+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2025-04-24T23:27:18.275+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/user_processing.py took 0.059 seconds
[2025-04-24T23:27:48.711+0000] {processor.py:186} INFO - Started process (PID=365) to work on /opt/airflow/dags/user_processing.py
[2025-04-24T23:27:48.714+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2025-04-24T23:27:48.719+0000] {logging_mixin.py:190} INFO - [2025-04-24T23:27:48.719+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2025-04-24T23:27:48.762+0000] {logging_mixin.py:190} INFO - [2025-04-24T23:27:48.751+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 4, in <module>
    from airflow.providers.http.operators.http import SimpleHttpOperator
ImportError: cannot import name 'SimpleHttpOperator' from 'airflow.providers.http.operators.http' (/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/http/operators/http.py)
[2025-04-24T23:27:48.769+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2025-04-24T23:27:48.786+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/user_processing.py took 0.082 seconds
[2025-04-24T23:28:19.216+0000] {processor.py:186} INFO - Started process (PID=373) to work on /opt/airflow/dags/user_processing.py
[2025-04-24T23:28:19.217+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2025-04-24T23:28:19.220+0000] {logging_mixin.py:190} INFO - [2025-04-24T23:28:19.220+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2025-04-24T23:28:19.245+0000] {logging_mixin.py:190} INFO - [2025-04-24T23:28:19.238+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 4, in <module>
    from airflow.providers.http.operators.http import SimpleHttpOperator
ImportError: cannot import name 'SimpleHttpOperator' from 'airflow.providers.http.operators.http' (/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/http/operators/http.py)
[2025-04-24T23:28:19.251+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2025-04-24T23:28:19.267+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/user_processing.py took 0.058 seconds
[2025-04-24T23:28:49.677+0000] {processor.py:186} INFO - Started process (PID=380) to work on /opt/airflow/dags/user_processing.py
[2025-04-24T23:28:49.678+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2025-04-24T23:28:49.682+0000] {logging_mixin.py:190} INFO - [2025-04-24T23:28:49.682+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2025-04-24T23:28:49.714+0000] {logging_mixin.py:190} INFO - [2025-04-24T23:28:49.705+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 4, in <module>
    from airflow.providers.http.operators.http import SimpleHttpOperator
ImportError: cannot import name 'SimpleHttpOperator' from 'airflow.providers.http.operators.http' (/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/http/operators/http.py)
[2025-04-24T23:28:49.720+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2025-04-24T23:28:49.752+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/user_processing.py took 0.086 seconds
[2025-04-24T23:29:20.139+0000] {processor.py:186} INFO - Started process (PID=388) to work on /opt/airflow/dags/user_processing.py
[2025-04-24T23:29:20.140+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2025-04-24T23:29:20.143+0000] {logging_mixin.py:190} INFO - [2025-04-24T23:29:20.142+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2025-04-24T23:29:20.165+0000] {logging_mixin.py:190} INFO - [2025-04-24T23:29:20.159+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 4, in <module>
    from airflow.providers.http.operators.http import SimpleHttpOperator
ImportError: cannot import name 'SimpleHttpOperator' from 'airflow.providers.http.operators.http' (/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/http/operators/http.py)
[2025-04-24T23:29:20.168+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2025-04-24T23:29:20.183+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/user_processing.py took 0.050 seconds
[2025-04-24T23:29:50.692+0000] {processor.py:186} INFO - Started process (PID=397) to work on /opt/airflow/dags/user_processing.py
[2025-04-24T23:29:50.694+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2025-04-24T23:29:50.697+0000] {logging_mixin.py:190} INFO - [2025-04-24T23:29:50.697+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2025-04-24T23:29:50.726+0000] {logging_mixin.py:190} INFO - [2025-04-24T23:29:50.719+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 4, in <module>
    from airflow.providers.http.operators.http import SimpleHttpOperator
ImportError: cannot import name 'SimpleHttpOperator' from 'airflow.providers.http.operators.http' (/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/http/operators/http.py)
[2025-04-24T23:29:50.729+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2025-04-24T23:29:50.749+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/user_processing.py took 0.064 seconds
[2025-04-24T23:30:21.202+0000] {processor.py:186} INFO - Started process (PID=405) to work on /opt/airflow/dags/user_processing.py
[2025-04-24T23:30:21.203+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2025-04-24T23:30:21.206+0000] {logging_mixin.py:190} INFO - [2025-04-24T23:30:21.206+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2025-04-24T23:30:21.229+0000] {logging_mixin.py:190} INFO - [2025-04-24T23:30:21.223+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 4, in <module>
    from airflow.providers.http.operators.http import SimpleHttpOperator
ImportError: cannot import name 'SimpleHttpOperator' from 'airflow.providers.http.operators.http' (/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/http/operators/http.py)
[2025-04-24T23:30:21.232+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2025-04-24T23:30:21.248+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/user_processing.py took 0.050 seconds
[2025-04-24T23:30:51.690+0000] {processor.py:186} INFO - Started process (PID=413) to work on /opt/airflow/dags/user_processing.py
[2025-04-24T23:30:51.691+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2025-04-24T23:30:51.694+0000] {logging_mixin.py:190} INFO - [2025-04-24T23:30:51.693+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2025-04-24T23:30:51.711+0000] {logging_mixin.py:190} INFO - [2025-04-24T23:30:51.706+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 4, in <module>
    from airflow.providers.http.operators.http import SimpleHttpOperator
ImportError: cannot import name 'SimpleHttpOperator' from 'airflow.providers.http.operators.http' (/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/http/operators/http.py)
[2025-04-24T23:30:51.713+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2025-04-24T23:30:51.728+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/user_processing.py took 0.043 seconds
[2025-04-24T23:31:22.206+0000] {processor.py:186} INFO - Started process (PID=421) to work on /opt/airflow/dags/user_processing.py
[2025-04-24T23:31:22.208+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2025-04-24T23:31:22.211+0000] {logging_mixin.py:190} INFO - [2025-04-24T23:31:22.210+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2025-04-24T23:31:22.238+0000] {logging_mixin.py:190} INFO - [2025-04-24T23:31:22.230+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 4, in <module>
    from airflow.providers.http.operators.http import SimpleHttpOperator
ImportError: cannot import name 'SimpleHttpOperator' from 'airflow.providers.http.operators.http' (/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/http/operators/http.py)
[2025-04-24T23:31:22.241+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2025-04-24T23:31:22.264+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/user_processing.py took 0.064 seconds
[2025-04-24T23:31:52.665+0000] {processor.py:186} INFO - Started process (PID=429) to work on /opt/airflow/dags/user_processing.py
[2025-04-24T23:31:52.667+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2025-04-24T23:31:52.668+0000] {logging_mixin.py:190} INFO - [2025-04-24T23:31:52.668+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2025-04-24T23:31:52.687+0000] {logging_mixin.py:190} INFO - [2025-04-24T23:31:52.681+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 4, in <module>
    from airflow.providers.http.operators.http import SimpleHttpOperator
ImportError: cannot import name 'SimpleHttpOperator' from 'airflow.providers.http.operators.http' (/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/http/operators/http.py)
[2025-04-24T23:31:52.689+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2025-04-24T23:31:52.705+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/user_processing.py took 0.046 seconds
[2025-04-24T23:32:23.177+0000] {processor.py:186} INFO - Started process (PID=437) to work on /opt/airflow/dags/user_processing.py
[2025-04-24T23:32:23.178+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2025-04-24T23:32:23.181+0000] {logging_mixin.py:190} INFO - [2025-04-24T23:32:23.181+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2025-04-24T23:32:23.205+0000] {logging_mixin.py:190} INFO - [2025-04-24T23:32:23.199+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 4, in <module>
    from airflow.providers.http.operators.http import SimpleHttpOperator
ImportError: cannot import name 'SimpleHttpOperator' from 'airflow.providers.http.operators.http' (/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/http/operators/http.py)
[2025-04-24T23:32:23.208+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2025-04-24T23:32:23.238+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/user_processing.py took 0.068 seconds
[2025-04-24T23:32:53.627+0000] {processor.py:186} INFO - Started process (PID=445) to work on /opt/airflow/dags/user_processing.py
[2025-04-24T23:32:53.628+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2025-04-24T23:32:53.631+0000] {logging_mixin.py:190} INFO - [2025-04-24T23:32:53.630+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2025-04-24T23:32:53.650+0000] {logging_mixin.py:190} INFO - [2025-04-24T23:32:53.645+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 4, in <module>
    from airflow.providers.http.operators.http import SimpleHttpOperator
ImportError: cannot import name 'SimpleHttpOperator' from 'airflow.providers.http.operators.http' (/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/http/operators/http.py)
[2025-04-24T23:32:53.655+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2025-04-24T23:32:53.676+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/user_processing.py took 0.053 seconds
[2025-04-24T23:33:24.084+0000] {processor.py:186} INFO - Started process (PID=453) to work on /opt/airflow/dags/user_processing.py
[2025-04-24T23:33:24.085+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2025-04-24T23:33:24.087+0000] {logging_mixin.py:190} INFO - [2025-04-24T23:33:24.087+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2025-04-24T23:33:24.106+0000] {logging_mixin.py:190} INFO - [2025-04-24T23:33:24.100+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 4, in <module>
    from airflow.providers.http.operators.http import SimpleHttpOperator
ImportError: cannot import name 'SimpleHttpOperator' from 'airflow.providers.http.operators.http' (/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/http/operators/http.py)
[2025-04-24T23:33:24.112+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2025-04-24T23:33:24.127+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/user_processing.py took 0.049 seconds
[2025-04-24T23:33:54.554+0000] {processor.py:186} INFO - Started process (PID=461) to work on /opt/airflow/dags/user_processing.py
[2025-04-24T23:33:54.555+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2025-04-24T23:33:54.557+0000] {logging_mixin.py:190} INFO - [2025-04-24T23:33:54.557+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2025-04-24T23:33:54.584+0000] {logging_mixin.py:190} INFO - [2025-04-24T23:33:54.578+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 4, in <module>
    from airflow.providers.http.operators.http import SimpleHttpOperator
ImportError: cannot import name 'SimpleHttpOperator' from 'airflow.providers.http.operators.http' (/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/http/operators/http.py)
[2025-04-24T23:33:54.587+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2025-04-24T23:33:54.602+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/user_processing.py took 0.052 seconds
[2025-04-24T23:34:25.100+0000] {processor.py:186} INFO - Started process (PID=468) to work on /opt/airflow/dags/user_processing.py
[2025-04-24T23:34:25.101+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2025-04-24T23:34:25.102+0000] {logging_mixin.py:190} INFO - [2025-04-24T23:34:25.102+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2025-04-24T23:34:25.119+0000] {logging_mixin.py:190} INFO - [2025-04-24T23:34:25.114+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 4, in <module>
    from airflow.providers.http.operators.http import SimpleHttpOperator
ImportError: cannot import name 'SimpleHttpOperator' from 'airflow.providers.http.operators.http' (/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/http/operators/http.py)
[2025-04-24T23:34:25.121+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2025-04-24T23:34:25.135+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/user_processing.py took 0.041 seconds
[2025-04-24T23:34:55.578+0000] {processor.py:186} INFO - Started process (PID=476) to work on /opt/airflow/dags/user_processing.py
[2025-04-24T23:34:55.579+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2025-04-24T23:34:55.581+0000] {logging_mixin.py:190} INFO - [2025-04-24T23:34:55.581+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2025-04-24T23:34:55.603+0000] {logging_mixin.py:190} INFO - [2025-04-24T23:34:55.596+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 4, in <module>
    from airflow.providers.http.operators.http import SimpleHttpOperator
ImportError: cannot import name 'SimpleHttpOperator' from 'airflow.providers.http.operators.http' (/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/http/operators/http.py)
[2025-04-24T23:34:55.607+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2025-04-24T23:34:55.621+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/user_processing.py took 0.048 seconds
[2025-04-24T23:35:26.121+0000] {processor.py:186} INFO - Started process (PID=484) to work on /opt/airflow/dags/user_processing.py
[2025-04-24T23:35:26.122+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2025-04-24T23:35:26.124+0000] {logging_mixin.py:190} INFO - [2025-04-24T23:35:26.124+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2025-04-24T23:35:26.161+0000] {logging_mixin.py:190} INFO - [2025-04-24T23:35:26.156+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 4, in <module>
    from airflow.providers.http.operators.http import SimpleHttpOperator
ImportError: cannot import name 'SimpleHttpOperator' from 'airflow.providers.http.operators.http' (/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/http/operators/http.py)
[2025-04-24T23:35:26.164+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2025-04-24T23:35:26.181+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/user_processing.py took 0.065 seconds
[2025-04-24T23:35:56.665+0000] {processor.py:186} INFO - Started process (PID=492) to work on /opt/airflow/dags/user_processing.py
[2025-04-24T23:35:56.666+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2025-04-24T23:35:56.670+0000] {logging_mixin.py:190} INFO - [2025-04-24T23:35:56.669+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2025-04-24T23:35:56.712+0000] {logging_mixin.py:190} INFO - [2025-04-24T23:35:56.701+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 4, in <module>
    from airflow.providers.http.operators.http import SimpleHttpOperator
ImportError: cannot import name 'SimpleHttpOperator' from 'airflow.providers.http.operators.http' (/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/http/operators/http.py)
[2025-04-24T23:35:56.718+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2025-04-24T23:35:56.771+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/user_processing.py took 0.115 seconds
[2025-04-24T23:36:27.281+0000] {processor.py:186} INFO - Started process (PID=500) to work on /opt/airflow/dags/user_processing.py
[2025-04-24T23:36:27.282+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2025-04-24T23:36:27.286+0000] {logging_mixin.py:190} INFO - [2025-04-24T23:36:27.285+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2025-04-24T23:36:27.314+0000] {logging_mixin.py:190} INFO - [2025-04-24T23:36:27.308+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 4, in <module>
    from airflow.providers.http.operators.http import SimpleHttpOperator
ImportError: cannot import name 'SimpleHttpOperator' from 'airflow.providers.http.operators.http' (/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/http/operators/http.py)
[2025-04-24T23:36:27.316+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2025-04-24T23:36:27.335+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/user_processing.py took 0.062 seconds
[2025-04-24T23:36:57.717+0000] {processor.py:186} INFO - Started process (PID=508) to work on /opt/airflow/dags/user_processing.py
[2025-04-24T23:36:57.718+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2025-04-24T23:36:57.723+0000] {logging_mixin.py:190} INFO - [2025-04-24T23:36:57.722+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2025-04-24T23:36:57.750+0000] {logging_mixin.py:190} INFO - [2025-04-24T23:36:57.743+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 4, in <module>
    from airflow.providers.http.operators.http import SimpleHttpOperator
ImportError: cannot import name 'SimpleHttpOperator' from 'airflow.providers.http.operators.http' (/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/http/operators/http.py)
[2025-04-24T23:36:57.754+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2025-04-24T23:36:57.775+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/user_processing.py took 0.062 seconds
[2025-04-24T23:37:28.255+0000] {processor.py:186} INFO - Started process (PID=516) to work on /opt/airflow/dags/user_processing.py
[2025-04-24T23:37:28.259+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2025-04-24T23:37:28.265+0000] {logging_mixin.py:190} INFO - [2025-04-24T23:37:28.265+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2025-04-24T23:37:28.298+0000] {logging_mixin.py:190} INFO - [2025-04-24T23:37:28.291+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 4, in <module>
    from airflow.providers.http.operators.http import SimpleHttpOperator
ImportError: cannot import name 'SimpleHttpOperator' from 'airflow.providers.http.operators.http' (/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/http/operators/http.py)
[2025-04-24T23:37:28.302+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2025-04-24T23:37:28.319+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/user_processing.py took 0.071 seconds
[2025-04-24T23:37:58.744+0000] {processor.py:186} INFO - Started process (PID=524) to work on /opt/airflow/dags/user_processing.py
[2025-04-24T23:37:58.745+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2025-04-24T23:37:58.747+0000] {logging_mixin.py:190} INFO - [2025-04-24T23:37:58.747+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2025-04-24T23:37:58.771+0000] {logging_mixin.py:190} INFO - [2025-04-24T23:37:58.765+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 4, in <module>
    from airflow.providers.http.operators.http import SimpleHttpOperator
ImportError: cannot import name 'SimpleHttpOperator' from 'airflow.providers.http.operators.http' (/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/http/operators/http.py)
[2025-04-24T23:37:58.774+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2025-04-24T23:37:58.795+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/user_processing.py took 0.057 seconds
[2025-04-24T23:38:29.148+0000] {processor.py:186} INFO - Started process (PID=532) to work on /opt/airflow/dags/user_processing.py
[2025-04-24T23:38:29.149+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2025-04-24T23:38:29.153+0000] {logging_mixin.py:190} INFO - [2025-04-24T23:38:29.152+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2025-04-24T23:38:29.176+0000] {logging_mixin.py:190} INFO - [2025-04-24T23:38:29.169+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 4, in <module>
    from airflow.providers.http.operators.http import SimpleHttpOperator
ImportError: cannot import name 'SimpleHttpOperator' from 'airflow.providers.http.operators.http' (/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/http/operators/http.py)
[2025-04-24T23:38:29.179+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2025-04-24T23:38:29.204+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/user_processing.py took 0.061 seconds
[2025-04-24T23:38:59.605+0000] {processor.py:186} INFO - Started process (PID=540) to work on /opt/airflow/dags/user_processing.py
[2025-04-24T23:38:59.607+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2025-04-24T23:38:59.609+0000] {logging_mixin.py:190} INFO - [2025-04-24T23:38:59.609+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2025-04-24T23:38:59.634+0000] {logging_mixin.py:190} INFO - [2025-04-24T23:38:59.628+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 4, in <module>
    from airflow.providers.http.operators.http import SimpleHttpOperator
ImportError: cannot import name 'SimpleHttpOperator' from 'airflow.providers.http.operators.http' (/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/http/operators/http.py)
[2025-04-24T23:38:59.638+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2025-04-24T23:38:59.664+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/user_processing.py took 0.065 seconds
[2025-04-24T23:39:30.093+0000] {processor.py:186} INFO - Started process (PID=548) to work on /opt/airflow/dags/user_processing.py
[2025-04-24T23:39:30.096+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2025-04-24T23:39:30.100+0000] {logging_mixin.py:190} INFO - [2025-04-24T23:39:30.100+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2025-04-24T23:39:30.134+0000] {logging_mixin.py:190} INFO - [2025-04-24T23:39:30.122+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 4, in <module>
    from airflow.providers.http.operators.http import SimpleHttpOperator
ImportError: cannot import name 'SimpleHttpOperator' from 'airflow.providers.http.operators.http' (/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/http/operators/http.py)
[2025-04-24T23:39:30.140+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2025-04-24T23:39:30.187+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/user_processing.py took 0.107 seconds
[2025-04-24T23:40:00.756+0000] {processor.py:186} INFO - Started process (PID=556) to work on /opt/airflow/dags/user_processing.py
[2025-04-24T23:40:00.757+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2025-04-24T23:40:00.760+0000] {logging_mixin.py:190} INFO - [2025-04-24T23:40:00.760+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2025-04-24T23:40:00.790+0000] {logging_mixin.py:190} INFO - [2025-04-24T23:40:00.782+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 4, in <module>
    from airflow.providers.http.operators.http import SimpleHttpOperator
ImportError: cannot import name 'SimpleHttpOperator' from 'airflow.providers.http.operators.http' (/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/http/operators/http.py)
[2025-04-24T23:40:00.793+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2025-04-24T23:40:00.813+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/user_processing.py took 0.062 seconds
[2025-04-24T23:40:31.258+0000] {processor.py:186} INFO - Started process (PID=570) to work on /opt/airflow/dags/user_processing.py
[2025-04-24T23:40:31.261+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2025-04-24T23:40:31.268+0000] {logging_mixin.py:190} INFO - [2025-04-24T23:40:31.267+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2025-04-24T23:40:31.309+0000] {logging_mixin.py:190} INFO - [2025-04-24T23:40:31.299+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 4, in <module>
    from airflow.providers.http.operators.http import SimpleHttpOperator
ImportError: cannot import name 'SimpleHttpOperator' from 'airflow.providers.http.operators.http' (/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/http/operators/http.py)
[2025-04-24T23:40:31.315+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2025-04-24T23:40:31.354+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/user_processing.py took 0.106 seconds
[2025-04-24T23:41:01.778+0000] {processor.py:186} INFO - Started process (PID=578) to work on /opt/airflow/dags/user_processing.py
[2025-04-24T23:41:01.780+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2025-04-24T23:41:01.783+0000] {logging_mixin.py:190} INFO - [2025-04-24T23:41:01.783+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2025-04-24T23:41:01.815+0000] {logging_mixin.py:190} INFO - [2025-04-24T23:41:01.804+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 4, in <module>
    from airflow.providers.http.operators.http import SimpleHttpOperator
ImportError: cannot import name 'SimpleHttpOperator' from 'airflow.providers.http.operators.http' (/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/http/operators/http.py)
[2025-04-24T23:41:01.818+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2025-04-24T23:41:01.837+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/user_processing.py took 0.065 seconds
[2025-04-24T23:41:32.286+0000] {processor.py:186} INFO - Started process (PID=586) to work on /opt/airflow/dags/user_processing.py
[2025-04-24T23:41:32.287+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2025-04-24T23:41:32.291+0000] {logging_mixin.py:190} INFO - [2025-04-24T23:41:32.290+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2025-04-24T23:41:32.335+0000] {logging_mixin.py:190} INFO - [2025-04-24T23:41:32.324+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 4, in <module>
    from airflow.providers.http.operators.http import SimpleHttpOperator
ImportError: cannot import name 'SimpleHttpOperator' from 'airflow.providers.http.operators.http' (/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/http/operators/http.py)
[2025-04-24T23:41:32.340+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2025-04-24T23:41:32.370+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/user_processing.py took 0.095 seconds
[2025-04-24T23:42:02.854+0000] {processor.py:186} INFO - Started process (PID=594) to work on /opt/airflow/dags/user_processing.py
[2025-04-24T23:42:02.855+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2025-04-24T23:42:02.858+0000] {logging_mixin.py:190} INFO - [2025-04-24T23:42:02.858+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2025-04-24T23:42:02.896+0000] {logging_mixin.py:190} INFO - [2025-04-24T23:42:02.885+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 4, in <module>
    from airflow.providers.http.operators.http import SimpleHttpOperator
ImportError: cannot import name 'SimpleHttpOperator' from 'airflow.providers.http.operators.http' (/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/http/operators/http.py)
[2025-04-24T23:42:02.900+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2025-04-24T23:42:02.922+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/user_processing.py took 0.073 seconds
[2025-04-24T23:42:33.313+0000] {processor.py:186} INFO - Started process (PID=602) to work on /opt/airflow/dags/user_processing.py
[2025-04-24T23:42:33.315+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2025-04-24T23:42:33.317+0000] {logging_mixin.py:190} INFO - [2025-04-24T23:42:33.317+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2025-04-24T23:42:33.352+0000] {logging_mixin.py:190} INFO - [2025-04-24T23:42:33.339+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 4, in <module>
    from airflow.providers.http.operators.http import SimpleHttpOperator
ImportError: cannot import name 'SimpleHttpOperator' from 'airflow.providers.http.operators.http' (/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/http/operators/http.py)
[2025-04-24T23:42:33.355+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2025-04-24T23:42:33.381+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/user_processing.py took 0.079 seconds
[2025-04-24T23:43:03.835+0000] {processor.py:186} INFO - Started process (PID=610) to work on /opt/airflow/dags/user_processing.py
[2025-04-24T23:43:03.836+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2025-04-24T23:43:03.839+0000] {logging_mixin.py:190} INFO - [2025-04-24T23:43:03.839+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2025-04-24T23:43:03.874+0000] {logging_mixin.py:190} INFO - [2025-04-24T23:43:03.865+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 4, in <module>
    from airflow.providers.http.operators.http import SimpleHttpOperator
ImportError: cannot import name 'SimpleHttpOperator' from 'airflow.providers.http.operators.http' (/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/http/operators/http.py)
[2025-04-24T23:43:03.877+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2025-04-24T23:43:03.899+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/user_processing.py took 0.072 seconds
[2025-04-24T23:43:34.385+0000] {processor.py:186} INFO - Started process (PID=618) to work on /opt/airflow/dags/user_processing.py
[2025-04-24T23:43:34.386+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2025-04-24T23:43:34.390+0000] {logging_mixin.py:190} INFO - [2025-04-24T23:43:34.389+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2025-04-24T23:43:34.424+0000] {logging_mixin.py:190} INFO - [2025-04-24T23:43:34.414+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 4, in <module>
    from airflow.providers.http.operators.http import SimpleHttpOperator
ImportError: cannot import name 'SimpleHttpOperator' from 'airflow.providers.http.operators.http' (/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/http/operators/http.py)
[2025-04-24T23:43:34.427+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2025-04-24T23:43:34.445+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/user_processing.py took 0.065 seconds
[2025-04-24T23:44:04.879+0000] {processor.py:186} INFO - Started process (PID=626) to work on /opt/airflow/dags/user_processing.py
[2025-04-24T23:44:04.881+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2025-04-24T23:44:04.884+0000] {logging_mixin.py:190} INFO - [2025-04-24T23:44:04.884+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2025-04-24T23:44:04.924+0000] {logging_mixin.py:190} INFO - [2025-04-24T23:44:04.914+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 4, in <module>
    from airflow.providers.http.operators.http import SimpleHttpOperator
ImportError: cannot import name 'SimpleHttpOperator' from 'airflow.providers.http.operators.http' (/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/http/operators/http.py)
[2025-04-24T23:44:04.928+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2025-04-24T23:44:04.956+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/user_processing.py took 0.084 seconds
[2025-04-24T23:44:35.536+0000] {processor.py:186} INFO - Started process (PID=634) to work on /opt/airflow/dags/user_processing.py
[2025-04-24T23:44:35.543+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2025-04-24T23:44:35.552+0000] {logging_mixin.py:190} INFO - [2025-04-24T23:44:35.551+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2025-04-24T23:44:35.631+0000] {logging_mixin.py:190} INFO - [2025-04-24T23:44:35.615+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 4, in <module>
    from airflow.providers.http.operators.http import SimpleHttpOperator
ImportError: cannot import name 'SimpleHttpOperator' from 'airflow.providers.http.operators.http' (/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/http/operators/http.py)
[2025-04-24T23:44:35.639+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2025-04-24T23:44:35.665+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/user_processing.py took 0.139 seconds
[2025-04-24T23:45:06.213+0000] {processor.py:186} INFO - Started process (PID=642) to work on /opt/airflow/dags/user_processing.py
[2025-04-24T23:45:06.215+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2025-04-24T23:45:06.222+0000] {logging_mixin.py:190} INFO - [2025-04-24T23:45:06.221+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2025-04-24T23:45:06.258+0000] {logging_mixin.py:190} INFO - [2025-04-24T23:45:06.249+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 4, in <module>
    from airflow.providers.http.operators.http import SimpleHttpOperator
ImportError: cannot import name 'SimpleHttpOperator' from 'airflow.providers.http.operators.http' (/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/http/operators/http.py)
[2025-04-24T23:45:06.263+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2025-04-24T23:45:06.291+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/user_processing.py took 0.093 seconds
[2025-04-24T23:45:36.730+0000] {processor.py:186} INFO - Started process (PID=650) to work on /opt/airflow/dags/user_processing.py
[2025-04-24T23:45:36.731+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2025-04-24T23:45:36.733+0000] {logging_mixin.py:190} INFO - [2025-04-24T23:45:36.733+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2025-04-24T23:45:36.756+0000] {logging_mixin.py:190} INFO - [2025-04-24T23:45:36.751+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 4, in <module>
    from airflow.providers.http.operators.http import SimpleHttpOperator
ImportError: cannot import name 'SimpleHttpOperator' from 'airflow.providers.http.operators.http' (/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/http/operators/http.py)
[2025-04-24T23:45:36.759+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2025-04-24T23:45:36.776+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/user_processing.py took 0.051 seconds
[2025-04-24T23:46:07.237+0000] {processor.py:186} INFO - Started process (PID=657) to work on /opt/airflow/dags/user_processing.py
[2025-04-24T23:46:07.239+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2025-04-24T23:46:07.241+0000] {logging_mixin.py:190} INFO - [2025-04-24T23:46:07.241+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2025-04-24T23:46:07.268+0000] {logging_mixin.py:190} INFO - [2025-04-24T23:46:07.260+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 4, in <module>
    from airflow.providers.http.operators.http import SimpleHttpOperator
ImportError: cannot import name 'SimpleHttpOperator' from 'airflow.providers.http.operators.http' (/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/http/operators/http.py)
[2025-04-24T23:46:07.272+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2025-04-24T23:46:07.295+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/user_processing.py took 0.066 seconds
[2025-04-24T23:46:37.772+0000] {processor.py:186} INFO - Started process (PID=665) to work on /opt/airflow/dags/user_processing.py
[2025-04-24T23:46:37.774+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2025-04-24T23:46:37.777+0000] {logging_mixin.py:190} INFO - [2025-04-24T23:46:37.776+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2025-04-24T23:46:37.809+0000] {logging_mixin.py:190} INFO - [2025-04-24T23:46:37.801+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 4, in <module>
    from airflow.providers.http.operators.http import SimpleHttpOperator
ImportError: cannot import name 'SimpleHttpOperator' from 'airflow.providers.http.operators.http' (/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/http/operators/http.py)
[2025-04-24T23:46:37.813+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2025-04-24T23:46:37.847+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/user_processing.py took 0.081 seconds
[2025-04-24T23:47:08.237+0000] {processor.py:186} INFO - Started process (PID=673) to work on /opt/airflow/dags/user_processing.py
[2025-04-24T23:47:08.239+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2025-04-24T23:47:08.241+0000] {logging_mixin.py:190} INFO - [2025-04-24T23:47:08.241+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2025-04-24T23:47:08.279+0000] {logging_mixin.py:190} INFO - [2025-04-24T23:47:08.270+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 4, in <module>
    from airflow.providers.http.operators.http import SimpleHttpOperator
ImportError: cannot import name 'SimpleHttpOperator' from 'airflow.providers.http.operators.http' (/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/http/operators/http.py)
[2025-04-24T23:47:08.284+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2025-04-24T23:47:08.304+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/user_processing.py took 0.074 seconds
[2025-04-24T23:47:38.744+0000] {processor.py:186} INFO - Started process (PID=681) to work on /opt/airflow/dags/user_processing.py
[2025-04-24T23:47:38.745+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2025-04-24T23:47:38.750+0000] {logging_mixin.py:190} INFO - [2025-04-24T23:47:38.750+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2025-04-24T23:47:38.777+0000] {logging_mixin.py:190} INFO - [2025-04-24T23:47:38.771+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 4, in <module>
    from airflow.providers.http.operators.http import SimpleHttpOperator
ImportError: cannot import name 'SimpleHttpOperator' from 'airflow.providers.http.operators.http' (/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/http/operators/http.py)
[2025-04-24T23:47:38.781+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2025-04-24T23:47:38.803+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/user_processing.py took 0.064 seconds
[2025-04-24T23:48:09.243+0000] {processor.py:186} INFO - Started process (PID=689) to work on /opt/airflow/dags/user_processing.py
[2025-04-24T23:48:09.244+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2025-04-24T23:48:09.248+0000] {logging_mixin.py:190} INFO - [2025-04-24T23:48:09.247+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2025-04-24T23:48:09.277+0000] {logging_mixin.py:190} INFO - [2025-04-24T23:48:09.270+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 4, in <module>
    from airflow.providers.http.operators.http import SimpleHttpOperator
ImportError: cannot import name 'SimpleHttpOperator' from 'airflow.providers.http.operators.http' (/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/http/operators/http.py)
[2025-04-24T23:48:09.281+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2025-04-24T23:48:09.304+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/user_processing.py took 0.065 seconds
[2025-04-24T23:48:39.769+0000] {processor.py:186} INFO - Started process (PID=697) to work on /opt/airflow/dags/user_processing.py
[2025-04-24T23:48:39.770+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2025-04-24T23:48:39.773+0000] {logging_mixin.py:190} INFO - [2025-04-24T23:48:39.772+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2025-04-24T23:48:39.800+0000] {logging_mixin.py:190} INFO - [2025-04-24T23:48:39.791+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 4, in <module>
    from airflow.providers.http.operators.http import SimpleHttpOperator
ImportError: cannot import name 'SimpleHttpOperator' from 'airflow.providers.http.operators.http' (/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/http/operators/http.py)
[2025-04-24T23:48:39.804+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2025-04-24T23:48:39.835+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/user_processing.py took 0.073 seconds
[2025-04-24T23:49:10.340+0000] {processor.py:186} INFO - Started process (PID=705) to work on /opt/airflow/dags/user_processing.py
[2025-04-24T23:49:10.343+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2025-04-24T23:49:10.356+0000] {logging_mixin.py:190} INFO - [2025-04-24T23:49:10.353+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2025-04-24T23:49:10.438+0000] {logging_mixin.py:190} INFO - [2025-04-24T23:49:10.431+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 4, in <module>
    from airflow.providers.http.operators.http import SimpleHttpOperator
ImportError: cannot import name 'SimpleHttpOperator' from 'airflow.providers.http.operators.http' (/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/http/operators/http.py)
[2025-04-24T23:49:10.442+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2025-04-24T23:49:10.459+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/user_processing.py took 0.129 seconds
[2025-04-24T23:49:40.872+0000] {processor.py:186} INFO - Started process (PID=713) to work on /opt/airflow/dags/user_processing.py
[2025-04-24T23:49:40.873+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2025-04-24T23:49:40.877+0000] {logging_mixin.py:190} INFO - [2025-04-24T23:49:40.877+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2025-04-24T23:49:40.907+0000] {logging_mixin.py:190} INFO - [2025-04-24T23:49:40.899+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 4, in <module>
    from airflow.providers.http.operators.http import SimpleHttpOperator
ImportError: cannot import name 'SimpleHttpOperator' from 'airflow.providers.http.operators.http' (/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/http/operators/http.py)
[2025-04-24T23:49:40.913+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2025-04-24T23:49:40.961+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/user_processing.py took 0.096 seconds
[2025-04-24T23:50:11.426+0000] {processor.py:186} INFO - Started process (PID=721) to work on /opt/airflow/dags/user_processing.py
[2025-04-24T23:50:11.428+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2025-04-24T23:50:11.430+0000] {logging_mixin.py:190} INFO - [2025-04-24T23:50:11.430+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2025-04-24T23:50:11.463+0000] {logging_mixin.py:190} INFO - [2025-04-24T23:50:11.454+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 4, in <module>
    from airflow.providers.http.operators.http import SimpleHttpOperator
ImportError: cannot import name 'SimpleHttpOperator' from 'airflow.providers.http.operators.http' (/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/http/operators/http.py)
[2025-04-24T23:50:11.466+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2025-04-24T23:50:11.484+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/user_processing.py took 0.062 seconds
[2025-04-24T23:50:41.908+0000] {processor.py:186} INFO - Started process (PID=729) to work on /opt/airflow/dags/user_processing.py
[2025-04-24T23:50:41.909+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2025-04-24T23:50:41.912+0000] {logging_mixin.py:190} INFO - [2025-04-24T23:50:41.911+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2025-04-24T23:50:41.944+0000] {logging_mixin.py:190} INFO - [2025-04-24T23:50:41.936+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 4, in <module>
    from airflow.providers.http.operators.http import SimpleHttpOperator
ImportError: cannot import name 'SimpleHttpOperator' from 'airflow.providers.http.operators.http' (/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/http/operators/http.py)
[2025-04-24T23:50:41.948+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2025-04-24T23:50:41.968+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/user_processing.py took 0.067 seconds
[2025-04-24T23:51:12.407+0000] {processor.py:186} INFO - Started process (PID=737) to work on /opt/airflow/dags/user_processing.py
[2025-04-24T23:51:12.410+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2025-04-24T23:51:12.412+0000] {logging_mixin.py:190} INFO - [2025-04-24T23:51:12.412+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2025-04-24T23:51:12.444+0000] {logging_mixin.py:190} INFO - [2025-04-24T23:51:12.436+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 4, in <module>
    from airflow.providers.http.operators.http import SimpleHttpOperator
ImportError: cannot import name 'SimpleHttpOperator' from 'airflow.providers.http.operators.http' (/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/http/operators/http.py)
[2025-04-24T23:51:12.447+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2025-04-24T23:51:12.463+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/user_processing.py took 0.065 seconds
[2025-04-24T23:51:42.838+0000] {processor.py:186} INFO - Started process (PID=745) to work on /opt/airflow/dags/user_processing.py
[2025-04-24T23:51:42.839+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2025-04-24T23:51:42.841+0000] {logging_mixin.py:190} INFO - [2025-04-24T23:51:42.841+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2025-04-24T23:51:42.864+0000] {logging_mixin.py:190} INFO - [2025-04-24T23:51:42.859+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 4, in <module>
    from airflow.providers.http.operators.http import SimpleHttpOperator
ImportError: cannot import name 'SimpleHttpOperator' from 'airflow.providers.http.operators.http' (/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/http/operators/http.py)
[2025-04-24T23:51:42.867+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2025-04-24T23:51:42.882+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/user_processing.py took 0.048 seconds
[2025-04-24T23:52:13.267+0000] {processor.py:186} INFO - Started process (PID=753) to work on /opt/airflow/dags/user_processing.py
[2025-04-24T23:52:13.268+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2025-04-24T23:52:13.272+0000] {logging_mixin.py:190} INFO - [2025-04-24T23:52:13.271+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2025-04-24T23:52:13.304+0000] {logging_mixin.py:190} INFO - [2025-04-24T23:52:13.298+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 4, in <module>
    from airflow.providers.http.operators.http import SimpleHttpOperator
ImportError: cannot import name 'SimpleHttpOperator' from 'airflow.providers.http.operators.http' (/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/http/operators/http.py)
[2025-04-24T23:52:13.307+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2025-04-24T23:52:13.328+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/user_processing.py took 0.066 seconds
[2025-04-24T23:52:43.774+0000] {processor.py:186} INFO - Started process (PID=761) to work on /opt/airflow/dags/user_processing.py
[2025-04-24T23:52:43.776+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2025-04-24T23:52:43.779+0000] {logging_mixin.py:190} INFO - [2025-04-24T23:52:43.778+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2025-04-24T23:52:43.808+0000] {logging_mixin.py:190} INFO - [2025-04-24T23:52:43.799+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 4, in <module>
    from airflow.providers.http.operators.http import SimpleHttpOperator
ImportError: cannot import name 'SimpleHttpOperator' from 'airflow.providers.http.operators.http' (/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/http/operators/http.py)
[2025-04-24T23:52:43.811+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2025-04-24T23:52:43.837+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/user_processing.py took 0.067 seconds
[2025-04-24T23:53:14.312+0000] {processor.py:186} INFO - Started process (PID=769) to work on /opt/airflow/dags/user_processing.py
[2025-04-24T23:53:14.313+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2025-04-24T23:53:14.315+0000] {logging_mixin.py:190} INFO - [2025-04-24T23:53:14.315+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2025-04-24T23:53:14.341+0000] {logging_mixin.py:190} INFO - [2025-04-24T23:53:14.333+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 4, in <module>
    from airflow.providers.http.operators.http import SimpleHttpOperator
ImportError: cannot import name 'SimpleHttpOperator' from 'airflow.providers.http.operators.http' (/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/http/operators/http.py)
[2025-04-24T23:53:14.346+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2025-04-24T23:53:14.367+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/user_processing.py took 0.064 seconds
[2025-04-24T23:53:44.796+0000] {processor.py:186} INFO - Started process (PID=777) to work on /opt/airflow/dags/user_processing.py
[2025-04-24T23:53:44.797+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2025-04-24T23:53:44.800+0000] {logging_mixin.py:190} INFO - [2025-04-24T23:53:44.800+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2025-04-24T23:53:44.826+0000] {logging_mixin.py:190} INFO - [2025-04-24T23:53:44.818+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 4, in <module>
    from airflow.providers.http.operators.http import SimpleHttpOperator
ImportError: cannot import name 'SimpleHttpOperator' from 'airflow.providers.http.operators.http' (/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/http/operators/http.py)
[2025-04-24T23:53:44.829+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2025-04-24T23:53:44.844+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/user_processing.py took 0.054 seconds
[2025-04-24T23:54:15.261+0000] {processor.py:186} INFO - Started process (PID=785) to work on /opt/airflow/dags/user_processing.py
[2025-04-24T23:54:15.263+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2025-04-24T23:54:15.267+0000] {logging_mixin.py:190} INFO - [2025-04-24T23:54:15.267+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2025-04-24T23:54:15.291+0000] {logging_mixin.py:190} INFO - [2025-04-24T23:54:15.284+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 4, in <module>
    from airflow.providers.http.operators.http import SimpleHttpOperator
ImportError: cannot import name 'SimpleHttpOperator' from 'airflow.providers.http.operators.http' (/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/http/operators/http.py)
[2025-04-24T23:54:15.295+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2025-04-24T23:54:15.313+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/user_processing.py took 0.058 seconds
[2025-04-24T23:54:45.770+0000] {processor.py:186} INFO - Started process (PID=793) to work on /opt/airflow/dags/user_processing.py
[2025-04-24T23:54:45.771+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2025-04-24T23:54:45.774+0000] {logging_mixin.py:190} INFO - [2025-04-24T23:54:45.773+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2025-04-24T23:54:45.827+0000] {logging_mixin.py:190} INFO - [2025-04-24T23:54:45.812+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 4, in <module>
    from airflow.providers.http.operators.http import SimpleHttpOperator
ImportError: cannot import name 'SimpleHttpOperator' from 'airflow.providers.http.operators.http' (/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/http/operators/http.py)
[2025-04-24T23:54:45.837+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2025-04-24T23:54:45.870+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/user_processing.py took 0.107 seconds
[2025-04-24T23:55:16.309+0000] {processor.py:186} INFO - Started process (PID=801) to work on /opt/airflow/dags/user_processing.py
[2025-04-24T23:55:16.310+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2025-04-24T23:55:16.312+0000] {logging_mixin.py:190} INFO - [2025-04-24T23:55:16.312+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2025-04-24T23:55:16.352+0000] {logging_mixin.py:190} INFO - [2025-04-24T23:55:16.344+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 4, in <module>
    from airflow.providers.http.operators.http import SimpleHttpOperator
ImportError: cannot import name 'SimpleHttpOperator' from 'airflow.providers.http.operators.http' (/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/http/operators/http.py)
[2025-04-24T23:55:16.357+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2025-04-24T23:55:16.380+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/user_processing.py took 0.081 seconds
[2025-04-24T23:55:46.770+0000] {processor.py:186} INFO - Started process (PID=809) to work on /opt/airflow/dags/user_processing.py
[2025-04-24T23:55:46.771+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2025-04-24T23:55:46.774+0000] {logging_mixin.py:190} INFO - [2025-04-24T23:55:46.774+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2025-04-24T23:55:46.808+0000] {logging_mixin.py:190} INFO - [2025-04-24T23:55:46.800+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 4, in <module>
    from airflow.providers.http.operators.http import SimpleHttpOperator
ImportError: cannot import name 'SimpleHttpOperator' from 'airflow.providers.http.operators.http' (/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/http/operators/http.py)
[2025-04-24T23:55:46.811+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2025-04-24T23:55:46.827+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/user_processing.py took 0.061 seconds
[2025-04-24T23:56:17.352+0000] {processor.py:186} INFO - Started process (PID=817) to work on /opt/airflow/dags/user_processing.py
[2025-04-24T23:56:17.353+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2025-04-24T23:56:17.355+0000] {logging_mixin.py:190} INFO - [2025-04-24T23:56:17.355+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2025-04-24T23:56:17.383+0000] {logging_mixin.py:190} INFO - [2025-04-24T23:56:17.375+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 4, in <module>
    from airflow.providers.http.operators.http import SimpleHttpOperator
ImportError: cannot import name 'SimpleHttpOperator' from 'airflow.providers.http.operators.http' (/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/http/operators/http.py)
[2025-04-24T23:56:17.386+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2025-04-24T23:56:17.406+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/user_processing.py took 0.061 seconds
[2025-04-24T23:56:47.882+0000] {processor.py:186} INFO - Started process (PID=825) to work on /opt/airflow/dags/user_processing.py
[2025-04-24T23:56:47.884+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2025-04-24T23:56:47.886+0000] {logging_mixin.py:190} INFO - [2025-04-24T23:56:47.886+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2025-04-24T23:56:47.914+0000] {logging_mixin.py:190} INFO - [2025-04-24T23:56:47.906+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 4, in <module>
    from airflow.providers.http.operators.http import SimpleHttpOperator
ImportError: cannot import name 'SimpleHttpOperator' from 'airflow.providers.http.operators.http' (/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/http/operators/http.py)
[2025-04-24T23:56:47.917+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2025-04-24T23:56:47.933+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/user_processing.py took 0.055 seconds
[2025-04-24T23:57:18.362+0000] {processor.py:186} INFO - Started process (PID=833) to work on /opt/airflow/dags/user_processing.py
[2025-04-24T23:57:18.364+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2025-04-24T23:57:18.366+0000] {logging_mixin.py:190} INFO - [2025-04-24T23:57:18.366+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2025-04-24T23:57:18.406+0000] {logging_mixin.py:190} INFO - [2025-04-24T23:57:18.397+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 4, in <module>
    from airflow.providers.http.operators.http import SimpleHttpOperator
ImportError: cannot import name 'SimpleHttpOperator' from 'airflow.providers.http.operators.http' (/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/http/operators/http.py)
[2025-04-24T23:57:18.411+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2025-04-24T23:57:18.430+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/user_processing.py took 0.074 seconds
[2025-04-24T23:57:48.858+0000] {processor.py:186} INFO - Started process (PID=840) to work on /opt/airflow/dags/user_processing.py
[2025-04-24T23:57:48.859+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2025-04-24T23:57:48.862+0000] {logging_mixin.py:190} INFO - [2025-04-24T23:57:48.861+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2025-04-24T23:57:48.901+0000] {logging_mixin.py:190} INFO - [2025-04-24T23:57:48.892+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 4, in <module>
    from airflow.providers.http.operators.http import SimpleHttpOperator
ImportError: cannot import name 'SimpleHttpOperator' from 'airflow.providers.http.operators.http' (/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/http/operators/http.py)
[2025-04-24T23:57:48.904+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2025-04-24T23:57:48.920+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/user_processing.py took 0.067 seconds
[2025-04-24T23:58:19.326+0000] {processor.py:186} INFO - Started process (PID=848) to work on /opt/airflow/dags/user_processing.py
[2025-04-24T23:58:19.327+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2025-04-24T23:58:19.329+0000] {logging_mixin.py:190} INFO - [2025-04-24T23:58:19.329+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2025-04-24T23:58:19.360+0000] {logging_mixin.py:190} INFO - [2025-04-24T23:58:19.351+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 4, in <module>
    from airflow.providers.http.operators.http import SimpleHttpOperator
ImportError: cannot import name 'SimpleHttpOperator' from 'airflow.providers.http.operators.http' (/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/http/operators/http.py)
[2025-04-24T23:58:19.364+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2025-04-24T23:58:19.381+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/user_processing.py took 0.059 seconds
[2025-04-24T23:58:49.804+0000] {processor.py:186} INFO - Started process (PID=856) to work on /opt/airflow/dags/user_processing.py
[2025-04-24T23:58:49.805+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2025-04-24T23:58:49.808+0000] {logging_mixin.py:190} INFO - [2025-04-24T23:58:49.808+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2025-04-24T23:58:49.841+0000] {logging_mixin.py:190} INFO - [2025-04-24T23:58:49.836+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 4, in <module>
    from airflow.providers.http.operators.http import SimpleHttpOperator
ImportError: cannot import name 'SimpleHttpOperator' from 'airflow.providers.http.operators.http' (/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/http/operators/http.py)
[2025-04-24T23:58:49.843+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2025-04-24T23:58:49.857+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/user_processing.py took 0.059 seconds
[2025-04-24T23:59:20.301+0000] {processor.py:186} INFO - Started process (PID=864) to work on /opt/airflow/dags/user_processing.py
[2025-04-24T23:59:20.303+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2025-04-24T23:59:20.310+0000] {logging_mixin.py:190} INFO - [2025-04-24T23:59:20.309+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2025-04-24T23:59:20.357+0000] {logging_mixin.py:190} INFO - [2025-04-24T23:59:20.345+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 4, in <module>
    from airflow.providers.http.operators.http import SimpleHttpOperator
ImportError: cannot import name 'SimpleHttpOperator' from 'airflow.providers.http.operators.http' (/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/http/operators/http.py)
[2025-04-24T23:59:20.362+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2025-04-24T23:59:20.390+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/user_processing.py took 0.098 seconds
[2025-04-24T23:59:50.911+0000] {processor.py:186} INFO - Started process (PID=872) to work on /opt/airflow/dags/user_processing.py
[2025-04-24T23:59:50.913+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2025-04-24T23:59:50.918+0000] {logging_mixin.py:190} INFO - [2025-04-24T23:59:50.917+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2025-04-24T23:59:50.949+0000] {logging_mixin.py:190} INFO - [2025-04-24T23:59:50.940+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 4, in <module>
    from airflow.providers.http.operators.http import SimpleHttpOperator
ImportError: cannot import name 'SimpleHttpOperator' from 'airflow.providers.http.operators.http' (/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/http/operators/http.py)
[2025-04-24T23:59:50.953+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2025-04-24T23:59:50.985+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/user_processing.py took 0.085 seconds
